### ISSUE TITLE
myql table scanner cannot stop if source db deletes data

### ISSUE THREAD

**Issue by ming535** [moiot/gravity#11]
We should consider start a snapshot consistent read.

**Comment by Ryan-Git** [comment]
it would be too expensive for large tables, and make parallel fetch quite difficult, if not impossible.  

I'd prefer a local comparison along with an optional remote one for non-numeric columns(e.g. select 'abc'>'abcd') instead.

**Comment by ming-relax** [comment]
The limitation of this `comparison`  is that it cannot handle the case when the source db update the scan column. For example, the source db update the primary key.

I think we should:

- Make it clear in the document that batch scan might have data inconsistent when the scan column changed in the source db

- Provide option for user to choose snapshot read

**Comment by Ryan-Git** [comment]
Why it can't stop?

**Comment by Ryan-Git** [comment]
Why it cannot stop? We'll finish the task if no rows returned from query. 
https://github.com/moiot/gravity/blob/bb844133dbb673daa40294606e72edde026ef751/pkg/inputs/mysqlbatch/mysql_table_scanner.go#L224
