### ISSUE TITLE
simplify the configure files

### ISSUE THREAD

**Issue by vkingnew** [moiot/gravity#111]
>In [[input.config.table-configs]] and  [[output.config.routes]] part when I have many tables  in database order_1,eg abcdefg table, I just want to the table abcd to synchronization.current I need to write 4 section config,I wish to simplization the config,like this ： 
>>[[output.config.routes]]
match-schema = "order_1"
match-table = ["a","b","c","d"]
target-schema = "OrderDB"
target-table = ["a","b","c","d"]

**Comment by Ryan-Git** [comment]
match-table could be refactored to support both string and string array, but target-table can't be easily changed.
but in this case, leave the target-table blank(which means keep the original table name) is just fine. so the result config would be 
```toml
[[output.config.routes]]
match-schema = "order_1"
match-table = ["a","b","c","d"]
target-schema = "OrderDB"
target-table = ""
```

**Comment by vkingnew** [comment]
Gravity version:
> ./gravity -V
Release Version (gravity): 0.0.1+git.
Git Commit Hash: 
Git Branch: 
UTC Build Time: 2019-03-12 12:21:13

at present it occurs:
>{"file":"mysql.go","level":"info","line":79,"msg":"[output-mysql] Using mysql-replace-engine","pipeline":"trd_mysql2tidb_change","time":"2019/03/14 15:20:16.016"}
{"file":"main.go","level":"fatal","line":75,"msg":"/usr/local/go/src/github.com/moiot/gravity/pkg/matchers/table_matchers.go:19: match-table only receives a string, you provided: [ProductSku ProductSkuSalePolicy]\n/usr/local/go/src/github.com/moiot/gravity/pkg/matchers/matchers.go:29: \n/usr/local/go/src/github.com/moiot/gravity/pkg/outputs/routers/mysql_router.go:57: \n/usr/local/go/src/github.com/moiot/gravity/pkg/outputs/mysql/mysql.go:91: \n/usr/local/go/src/github.com/moiot/gravity/pkg/app/server.go:56: ","pipeline":"trd_mysql2tidb_change","time":"2019/03/14 15:20:16.016"}

My test case like this:
>#目标库表：
>[output]
type = "mysql"
[output.config.target]
host = "172.17.14.19"
username = "root"
password = "xyz"
port = 4000
[output.config]
enable-ddl=true
>#分库分表合并
[[output.config.routes]]
match-schema = "jp_productsku_1"
match-table = ["ProductSku","ProductSkuSalePolicy"]
target-schema = "ProductDB"
target-table = ""
>[[output.config.routes]]
match-schema = "jp_productsku_2"
match-table = ["ProductSku","ProductSkuSalePolicy"]
target-schema = "ProductDB"
target-table = ""
>[[output.config.routes]]
match-schema = "jp_productsku_3"
match-table = ["ProductSku","ProductSkuSalePolicy"]
target-schema = "ProductDB"
target-table = ""
>#全局表
[[output.config.routes]]
match-schema = "jp_productsku_1"
match-table = "ProductInfo"
target-schema = "ProductDB"
target-table = "ProductInfo"

It's better to support regular expression in section "match-schema",like this ：
>match-schema = "jp_productsku_*"

**Comment by Ryan-Git** [comment]
the array like syntax hasn't been implemented yet...
`jp_productsku_*` is not a regex, it's like a glob, which is already supported.

**Comment by Ryan-Git** [comment]
@vkingnew 
now u could write match-table like this
```toml
match-table = "test_table_*"
match-table = ["a*", "b*"]
```
see https://github.com/moiot/gravity/blob/master/docs/2.0/07-matcher-en.md
