### ISSUE TITLE
[MapString] unknown type: int32

### ISSUE THREAD

**Issue by vkingnew** [moiot/gravity#112]
Gravity version:
># ./gravity -V
>Release Version (gravity): 0.0.1+git.
Git Commit Hash: 
Git Branch: 
UTC Build Time: 2019-03-12 12:21:13
the version may be 0.9.27, I clone the master branch and compiled by myself.

Error log：
>{"file":"mysql_table_scanner.go","level":"info","line":185,"msg":"[LoopInBatch] prepare current: [{Value:{String:1467178125170318497 Valid:true} Type: Column:id}]","pipeline":"crm_mysql2tidb","time":"2019/03/14 11:20:32.051"}
{"file":"cache.go","level":"fatal","line":63,"msg":"[defaultPositionCache] ticker flush failed: mysqlbatch.BatchPositionValueV1.TableStates: mysqlbatch.TableStatsV1.Done: ScannedCount: EstimatedRowCount: Current: Min: []mysqlbatch.TablePosition: [MapString] unknown type: int32, column: Id\n/usr/local/go/src/github.com/moiot/gravity/pkg/position_store/cache.go:229: \n/usr/local/go/src/github.com/moiot/gravity/pkg/position_store/cache.go:169: ","pipeline":"crm_mysql2tidb","time":"2019/03/14 11:20:32.694"}

configure file like this:
>#MySQL 到 TiDB 全量+增量同步
name="crm_mysql2tidb"
[input]
type = "mysql"
mode = "replication"
[input.config]
nr-scanner = 10
table-scan-batch = 10000
batch-per-second-limit = 1
max-full-dump-count = 10000
[input.config.source]
host = "172.16.1.86"
username = "_gravity"
password = "gravity"
port = 3310
[input.config.source-slave]
host = "172.16.1.87"
username = "_gravity"
password = "gravity"
port = 3310
>#需要扫描的表
>[[input.config.table-configs]]
schema = "yjp_broker"
table = "*"

>[[input.config.table-configs]]
schema = "yjp_office"
table = "*"

>[[input.config.table-configs]]
schema = "yjp_czbank"
table = "*"

>#目标库表：
>[output]
type = "mysql"
[output.config.target]
host = "172.17.14.19"
username = "root"
password = "yijiupi"
port = 4000

>[output.config]
enable-ddl=true

>[[output.config.routes]]
match-schema = "yjp_broker"
match-table = "*"
target-schema = "BrokerDB"
target-table = "*"

>[[output.config.routes]]
match-schema = "yjp_office"
match-table = "*"
target-schema = "OfficeDB"
target-table = "*"

>[[output.config.routes]]
match-schema = "yjp_czbank"
match-table = "*"
target-schema = "BankDB"
target-table = "*"

at TiDB I just create database,like this:
>create database BrokerDB;
create database OfficeDB;
create databse BankDB;
then i start gravity:
 /usr/local/gravity/gravity -config=/usr/local/gravity/scm_mysql2tidb.toml -http-addr=172.17.14.22:8091 -log-file=/usr/local/gravity/scm.log -L=info
 and the table define like this ：
>mysql> show create table brokerregionordersync\G
*************************** 1. row ***************************
       Table: brokerregionordersync
Create Table: CREATE TABLE `brokerregionordersync` (
  `id` bigint(20) NOT NULL COMMENT '主键',
  `orderid` bigint(20) NOT NULL COMMENT '订单ID',
  `orderitemid` bigint(20) NOT NULL COMMENT '订单项ID',
  `city_id` int(11) NOT NULL COMMENT '城市id',
  `state` tinyint(4) NOT NULL COMMENT '订单同步状态 1 下单 2 完成 3 取消 4 退货',
  `regionbrokerid` int(11) DEFAULT NULL COMMENT '专区经纪人id',
  `crmchannelid` bigint(20) DEFAULT NULL COMMENT 'CRM频道id',
  `salaryratio` decimal(4,2) DEFAULT NULL COMMENT '业绩系数',
  `returnorderid` bigint(20) DEFAULT NULL COMMENT '退货订单ID',
  `returnorderitemid` bigint(20) DEFAULT NULL COMMENT '退货订单项ID',
  `createtime` datetime NOT NULL COMMENT '创建时间',
  `lastmodifytime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `salarybrokerid` int(11) DEFAULT NULL COMMENT '业绩经纪人id',
  PRIMARY KEY (`id`),
  KEY `ix_orderid` (`orderid`) USING BTREE COMMENT '订单id',
  KEY `ix_regionbrokerid` (`regionbrokerid`) USING BTREE COMMENT '经纪人id',
  KEY `ix_city_id` (`city_id`) USING BTREE COMMENT '城市id',
  KEY `ix_orderitemid` (`orderitemid`) USING BTREE COMMENT '订单项id',
  KEY `ix_returnorderitemid` (`returnorderitemid`) USING BTREE COMMENT '退货单项id'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='经纪人多专区订单同步表'
1 row in set (0.00 sec)

conclusion：
> I guess the data type（bigint unsigned） in MySQL is not mapping well in Gravity soure code,so the error info is:unknown type: int32, column: Id

Please check.

**Comment by ming535** [comment]
@vkingnew this is is fixed with latest master

**Comment by vkingnew** [comment]
Thanks, I test on my test environment,it appears another error message,Like this ：
>{"file":"mysql_table_scanner.go","level":"info","line":185,"msg":"[LoopInBatch] prepare current: [{Value:1 Type: Column:Id}]","pipeline":"crm_mysql2tidb","time":"2019/03/18 10:15:09.663"}
{"file":"batch_table_scheduler.go","level":"info","line":259,"msg":"[batchScheduler.SubmitMsg] deleted new sliding window, key=`yjp_broker`.`bizusercomplaintbasicdata`","pipeline":"crm_mysql2tidb","time":"2019/03/18 10:15:09.791"}
{"file":"static_sliding_window.go","level":"info","line":177,"msg":"[staticSlidingWindow] closing","pipeline":"crm_mysql2tidb","time":"2019/03/18 10:15:09.791"}
{"file":"batch_table_scheduler.go","level":"info","line":263,"msg":"[batchScheduler.SubmitMsg] closed stream: `yjp_broker`.`bizusercomplaintbasicdata`","pipeline":"crm_mysql2tidb","time":"2019/03/18 10:15:09.791"}
{"file":"mysql_table_scanner.go","level":"fatal","line":298,"msg":"[LoopInBatch] failed finish batch scan: mysqlbatch.BatchPositionValueV1.TableStates: mysqlbatch.TableStatsV1.Done: ScannedCount: EstimatedRowCount: Current: Min: []mysqlbatch.TablePosition: [MapString] unknown type: int8, column: mallapptype\n/usr/local/go/src/github.com/moiot/gravity/pkg/position_store/cache.go:229: \n/usr/local/go/src/github.com/moiot/gravity/pkg/position_store/cache.go:169: \n/usr/local/go/src/github.com/moiot/gravity/pkg/inputs/helper/two_stage_input.go:261: \n/usr/local/go/src/github.com/moiot/gravity/pkg/inputs/mysqlbatch/mysql_table_scanner.go:325: ","pipeline":"crm_mysql2tidb","time":"2019/03/18 10:15:09.806"}
the column datatye is tinyint
`mallAppType` tinyint(4) DEFAULT NULL COMMENT 'APP类型',
