### ISSUE TITLE
Just want to synchronize special databases and tables ,however it scan full database

### ISSUE THREAD

**Issue by vkingnew** [moiot/gravity#113]
![bug](https://user-images.githubusercontent.com/5238970/54341654-52749200-4675-11e9-9711-c474108886d5.jpg)

I just want to synchronize special databases and tables in thousands of tables,like this ：
># 需要扫描的表
># - 必填
>[[input.config.table-configs]]
schema = "yjp_productsku_1"
table = "productsku,productinfo,ProductSkuSalePolicy"
>[[input.config.table-configs]]
schema = "yjp_productsku_2"
table = "productsku,ProductSkuSalePolicy"
>[[input.config.table-configs]]
schema = "yjp_prodcutsku_3"
table = "productsku,ProductSkuSalePolicy"
>[output]
type = "mysql"
>[output.config.target]
host = "172.17.14.19"
username = "root"
password = "xyz"
port = 4000
>[output.config]
enable-ddl=true
#分库分表合并
>[[output.config.routes]]
match-schema = "jp_productsku_1"
match-table = "ProductSku"
target-schema = "ProductDB"
target-table = ""
>[[output.config.routes]]
match-schema = "jp_productsku_1"
match-table = "ProductSkuSalePolicy"
target-schema = "ProductDB"
target-table = ""
>[[output.config.routes]]
match-schema = "jp_productsku_2"
match-table = "ProductSku"
target-schema = "ProductDB"
target-table = ""
>[[output.config.routes]]
match-schema = "jp_productsku_2"
match-table = "ProductSkuSalePolicy"
target-schema = "ProductDB"
target-table = ""
>[[output.config.routes]]
match-schema = "jp_productsku_3"
match-table = "ProductSku"
target-schema = "ProductDB"
target-table = ""
>[[output.config.routes]]
match-schema = "jp_productsku_3"
match-table = "ProductSkuSalePolicy"
target-schema = "ProductDB"
target-table = ""
>#全局表
>[[output.config.routes]]
match-schema = "jp_productsku_1"
match-table = "ProductInfo"
target-schema = "ProductDB"
target-table = "ProductInfo"

however by log or monitor,it scan all the database's table:
 and how to wite the configure file to synchronize the tables and database which I just want. by history data and incremental data. The other are not to synchronize.

**Comment by Ryan-Git** [comment]
because binlog has all table writes, the input component in stream mode will see all tables. but output won't write data that not configured, you could look at the output pane in dashboard to confirm it.
