### ISSUE TITLE
MySQL -->kafka data type decimal(M,N) not support

### ISSUE THREAD

**Issue by vkingnew** [moiot/gravity#124]
the value of MySQL  data type decimal(M,N)   to kafka,the data is unknonw.

the original data:
> ExactPayAmount: 142.00
 OrderAmount: 142.00
           PayableAmount: 142.00
            ReduceAmount: 0.00
         UseCouponAmount: 0.00
         GiveBonusAmount: 0.00

by gravity to kafka:
>{
  "version": "0.1",
  "database": "order_3",
  "table": "orders",
  "type": "insert",
  "ts": 1553479471,
  "time_zone": "Asia/Shanghai",
  "host": "",
  "data": {
    "Address_Id": "1293184",
    "City": "太原市",
    "City_Id": "704",
    "Contact": "郭*生",
    "CostWineScore": "[48 46 48 48]",
    "County": "小店区",
    "CreateTime": "2018-10-10 15:24:41",
    "CreateUserId": "408501",
    "DeliveryMode": "0",
    "DetailAddress": "御龙庭底******",
    "ExactPayAmount": "[49 52 50 46 48 48]",
    "GiveBonusAmount": "[48 46 48 48]",
    "GiveCouponAmount": "[48 46 48 48]",
    "GiveWineScore": "[48 46 48 48]",
    "HasPayment": "0",
    "Id": "704118101015312437",
    "IsTestOrder": "0",
    "LastModifyTime": "2019-01-27 00:05:00.1",
    "LastUpdateTime": "2018-10-12 10:19:00",
    "LastUpdateUserId": "891",
    "OrderAmount": "[49 52 50 46 48 48]",
    "OrderAttachedGiftRule_Id": null,
    "OrderAuditTime": null,
    "OrderBatch_Id": "704418101015312436",
    "OrderCancelTime": "2018-10-12 10:19:00",
    "OrderClassify": "0",
    "OrderCompleteTime": null,
    "OrderConfirmTime": "2018-10-10 15:24:41",
    "OrderCreateTime": "2018-10-10 15:24:41",
    "OrderDeliverTime": null,
    "OrderNo": "704828300340",
    "OrderPrintTime": null,
    "OrderReducationRule_Id": null,
    "OrderSyncTime": null,
    "OrderType": "0",
    "PayType": "0",
    "PayableAmount": "[49 52 50 46 48 48]",
    "PaymentState": null,
    "Phone": "1873457****",
    "ProductReduceAmount": "[48 46 48 48]",
    "Province": "山西省",
    "QrCodeFileId": null,
    "ReduceAmount": "[48 46 48 48]",
    "RemarkService": null,
    "RemarkUser": "",
    "SalesmanId": "762",
    "State": "8",
    "StateUser": "7",
    "Street": "平阳路西二巷",
    "SysRemark": "",
    "UseAwardBonusAmount": null,
    "UseBonusAmount": "[48 46 48 48]",
    "UseCouponAmount": "[48 46 48 48]",
    "UseCouponCodeAmount": "[48 46 48 48]",
    "UseRewardBonusAmount": "[48 46 48 48]",
    "UserCancelReason": null,
    "UserCompanyName": "生鲜超市****",
    "UserId": "408501",
    "UserMobileNo": "1873457****",
    "UserName": "郭*生",
    "Verison": "1.0.0",
    "ZipCode": null,
    "area_id": null,
    "onlineSalesmanDeptId": null,
    "onlineSalesmanId": null,
    "orderItemCount": "1",
    "pickup_warehouse_Id": "7041",
    "salesmanDeptId": "2",
    "selfPickUpReduceAmount": "[48 46 48 48]",
    "shop_id": null
  },
  "old": {},
  "pks": {
    "Id": "704118101015312437"
  }
}

unknow data:
>"ExactPayAmount": "[49 52 50 46 48 48]",
    "GiveBonusAmount": "[48 46 48 48]",
    "GiveCouponAmount": "[48 46 48 48]",
    "GiveWineScore": "[48 46 48 48]",

**Comment by vkingnew** [comment]
how about the progress of fixed this feature?

**Comment by Ryan-Git** [comment]
@ming-relax 
mysql batch doesn't handle decimal correctly. Maybe we can use https://github.com/jmoiron/sqlx to get the scanned map/slice.
