### ISSUE TITLE
数据迁移场景下的使用

### ISSUE THREAD

**Issue by zzkkll99** [moiot/gravity#126]
首先感谢作者的开源。在这里我想把gravity放到一个迁移的场景下进行使用。
这里问一下根据手册必要要在目标端创建跟源端一样的库及表结构才可以进行，请问这里可以不这样做吗？
方便的话可以提供一下微信或者qq群方便学习，交流。
谢谢， ^_^

**Comment by Ryan-Git** [comment]
mysql output 开启 ddl 的话会自动同步表结构，库要自己建。

![image](https://user-images.githubusercontent.com/5906907/55212627-5edb1c00-522b-11e9-996e-f4adae101395.png)

**Comment by zhangchangwei** [comment]
@Ryan-Git 求加群
