### ISSUE TITLE
Support MySQL/TiDB --> ElasticSearch

### ISSUE THREAD

**Issue by vkingnew** [moiot/gravity#127]
Do you have a plan to support transfer the data of MySQL and TiDB  to ElasticSearch?
ElasticSearch is more professional than mysql or tidb do fulltext index .

**Comment by kayaklee** [comment]
No plans yet, but I hope someone can support it by our plugin interface, and we will approve the feature.

**Comment by ScienJus** [comment]
Please assign this issue to me, I am working on it and will provide a wip pr during the week.

**Comment by Ryan-Git** [comment]
closed by #130
