### ISSUE TITLE
the master has purged binary logs containing GTIDs that the slave requires

### ISSUE THREAD

**Issue by zhanglei** [moiot/gravity#140]
使用过程中，停掉gravity一段时间后再启动复制，会出现错误:
ERROR 1236 (HY000): The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires.

查看http://mysql.taobao.org/monthly/2016/01/08/，有可能是这个问题引起，gravity内部是否会处理

**Comment by Ryan-Git** [comment]
贴一下 show master status 和 _gravity.gravity_positions 表的内容。

停掉再启动 gravity 会从上次停的地方继续。一种情况是 binlog 保存时间/容量不够了，日志被删了，那本来就无法同步了，需要把位点删了重来。

还有一种情况就是链接里的， mysql 主从切换，备机执行了一些管理命令，日志没有同步到新的主机（比如腾讯云 rds 的拓扑比较特殊，经常会这样），这时候虽然从 gtid 看缺失了日志，但并没有丢失数据。这就需要人工比对 gtid 修正了。

这个事情现在还没法自动化地处理，程序很难判断这个不同的 gtid 是否会导致丢数据，还是需要人工介入。

**Comment by zhanglei** [comment]
![image](https://user-images.githubusercontent.com/241508/56419485-f54faa00-62cc-11e9-84f3-0678ff2e702f.png)

_gravity.gravity_positions
{"current_position":{"binlog-name":"mysql-bin.001076","binlog-pos":724209153,"binlog-gtid":"27126afd-29ca-11e9-bf5a-b4969140ce40:1-27,c3f8fa79-0ca7-11e9-92ae-e4434b3b2086:1-1221492524"},"start_position":null}

**Comment by Ryan-Git** [comment]
这就是日志没了呀，1221492524 比 purged 小了，没啥办法，_gravity.gravity_positions 里这行记录删了重来吧。

**Comment by zhanglei** [comment]
问题引起的原因定位到了，是因为最新binlog值未刷到_gravity.gravity_positions表里，重启之前拿的还是很久之前存储在_gravity.gravity_positions表binlog位置去同步数据，看了下源码在停止gravity时未把当前最新的binlog位置刷到_gravity.gravity_positions表保存

**Comment by Ryan-Git** [comment]
@zhanglei
应该不是这个问题，退出时候刷位点的https://github.com/moiot/gravity/blob/master/pkg/position_cache/cache.go#L67

**Comment by zhanglei** [comment]
binlog_tailer.go在处理binlog事件RotateEvent、GTIDEvent时，会改变currentPosition位置，这两个事件不会触发AfterMsgCommit，也就是不会调用UpdateCurrentPositionValue改变cache里的值

**Comment by Ryan-Git** [comment]
@zhanglei 
这两个事件本来就不推进 gtid，position 是 position

**Comment by zhanglei** [comment]
XIDEvent事件会把binlog位置写入AppendMsgTxnBuffer，GTIDEvent会有一个ClearMsgTxnBuffer，FlushMsgTxnBuffer时，拿到xid事件的概率很少，同时emitter.Emit在处理xid事件也有问题filter时未做xid事件过滤

**Comment by Ryan-Git** [comment]
每个事务提交都有 xid，概率一点也不小（我们还有心跳，即使业务没有写入，位点也是不断推进的）。要么你是超长事务，中间暂停了，那没办法，重启只能重来，gtid 本身就是这样设计的，跟 binlog name + pos 的方式不一样。

**Comment by Ryan-Git** [comment]
filter 不过滤 xid 是故意的，xid 才能推进位点，过滤了拿啥推进。。。

**Comment by zhanglei** [comment]
![image](https://user-images.githubusercontent.com/241508/56556513-cbe39680-65ca-11e9-98b5-3a964b9d1f6c.png)
![image](https://user-images.githubusercontent.com/241508/56556564-e74ea180-65ca-11e9-95ce-d44f4831309a.png)
全部是ROWS_EVENT，没有XIDEvent

**Comment by zhanglei** [comment]
![image](https://user-images.githubusercontent.com/241508/56556797-7e1b5e00-65cb-11e9-9a67-096ac97d183d.png)
![image](https://user-images.githubusercontent.com/241508/56556817-8bd0e380-65cb-11e9-8dee-4d734dd4e148.png)

**Comment by Ryan-Git** [comment]
那就是你开了大事务没提交呀

**Comment by Ryan-Git** [comment]
这图里位点不是更新了吗

**Comment by Ryan-Git** [comment]
你的完整配置贴一下？像是配了什么 filter 把 xid 过滤掉了。

**Comment by zhanglei** [comment]
binlog有XIDEvent事件，只是处理时有问题，看上面的XIDEvent截图

**Comment by zhanglei** [comment]
![image](https://user-images.githubusercontent.com/241508/56558390-22ec6a00-65d1-11e9-8c92-98b1f4590626.png)
[[filters]]
type = "accept"
[filters.config]
match-schema = "^tos_goods_v2_[0-9]+$"
match-table = "^tb_goods_[0-9]+$"
match-dml-op = ["insert"]

**Comment by zhanglei** [comment]
match-schema,match-table匹配因业务需要有调整源码为正则

**Comment by Ryan-Git** [comment]
是有个bug，filter 不应该对内部消息过滤。

**Comment by Ryan-Git** [comment]
另外如果 output 换回 kafka 的话其实不需要在 filter 里指定 match-schema 和 match-table 的，没有路由的会直接跳过。

**Comment by zhanglei** [comment]
赞！！！实际业务生产环境中有配置路由的.

还有一个问题，比较难复现:
github.com/moiot/gravity/pkg/inputs/helper.(*twoStagePositionCache).Get(0xc0005a3e90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/mysql-tool/gravity/pkg/inputs/helper/two_stage_input.go:245 +0x1fe
github.com/moiot/gravity/pkg/inputs/mysqlbatch.PutCurrentPos(0x1cf27a0, 0xc0005a3e90, 0xc001c3cd60, 0x1b, 0xc002813830, 0x1, 0x1, 0xc0005c4d01, 0x0, 0x0)
	/opt/mysql-tool/gravity/pkg/inputs/mysqlbatch/position_value.go:392 +0xc1
github.com/moiot/gravity/pkg/inputs/mysqlbatch.(*TableScanner).AfterMsgCommit(0xc0005a4000, 0xc002042b60, 0xa, 0x7ff6016a3440)
	/opt/mysql-tool/gravity/pkg/inputs/mysqlbatch/mysql_table_scanner.go:413 +0x99
github.com/moiot/gravity/pkg/inputs/mysqlbatch.(*TableScanner).AfterMsgCommit-fm(0xc002042b60, 0x1, 0x2)
	/opt/mysql-tool/gravity/pkg/inputs/mysqlbatch/mysql_table_scanner.go:281 +0x34
github.com/moiot/gravity/pkg/core.(*Msg).BeforeWindowMoveForward(0xc002042b60)
	/opt/mysql-tool/gravity/pkg/core/msg.go:85 +0x55
github.com/moiot/gravity/pkg/sliding_window.(*staticSlidingWindow).start(0xc0005c43c0)
	/opt/mysql-tool/gravity/pkg/sliding_window/static_sliding_window.go:166 +0x1dc
created by github.com/moiot/gravity/pkg/sliding_window.NewStaticSlidingWindow
	/opt/mysql-tool/gravity/pkg/sliding_window/static_sliding_window.go:210 +0x158

出现在replication模式，分析了原因，应该是出现在从batch切换到stream瞬间

**Comment by Ryan-Git** [comment]
就是消息不匹配路由的话会忽略，不需要再设置 filter 去忽略。

是手动取消时候报这个错还是正常在跑？

**Comment by zhanglei** [comment]
正常在跑情况，出现的概率很小
