### ISSUE TITLE
create internal table in input plugin

### ISSUE THREAD

**Issue by ming535** [moiot/gravity#173]
Create _gravity.gravity_txn_tags in the input plugin.

**Comment by zhangchangwei** [comment]
@ming-relax @Ryan-Git  可以提供下微信群吗？咨询一下关于安装的问题

**Comment by Ryan-Git** [comment]
@zhangchangwei 
![image](https://user-images.githubusercontent.com/5906907/59892082-42a1e200-940a-11e9-89ff-da1ecbd1c847.png)
