### ISSUE TITLE
文档太简单了，能否补充一下，包括集群配置的文档，schema store如何配置

### ISSUE THREAD

**Issue by selectliu** [moiot/gravity#189]
文档太简单了，能否补充一下，包括集群使用相关的文档，schema store如何配置

**Comment by selectliu** [comment]
能否给个微信群地址，之前的二维码过期了

**Comment by Ryan-Git** [comment]
集群在 https://github.com/moiot/gravity-operator, helm 装完按提示打开 admin 就能用了。
schema store 是指要配置什么？

**Comment by Ryan-Git** [comment]
![image](https://user-images.githubusercontent.com/5906907/61289813-d6de4980-a7fc-11e9-8e1c-42b4cd82eb26.png)

**Comment by CrazyNash** [comment]
这个微信群还能加吗？ @Ryan-Git

**Comment by Ryan-Git** [comment]
@CrazyNash 过期了，换个。

![image](https://user-images.githubusercontent.com/5906907/68464757-1ddcc880-024c-11ea-8aa9-b42e5744351e.png)
