### ISSUE TITLE
Does merge sharding tables take DDL into  consideration?

### ISSUE THREAD

**Issue by louishust** [moiot/gravity#199]
If merge sharding tables from 3 input source, into one mysql, if there is a same DDL in the 3 sources binlog, will gravity wait all binlog and just execute the DDL one time?
table a table t1 have c1 and c2 columns.
The binlog in 3 shard data souce like below:

| shard1 | shard2 | shard3 |
| ---- | ---- | -----|
|  1: insert t1(1,1)      |    2: insert t2 (2,2)   |  3: insert t3(3,3)   |
|  4: alter table t1 drop column c1| 5: alter table t1 drop column c1| 6: alter table t1 drop column c1|

if the execute order is 1->4->2, then the 2 will be error.

**Comment by Ryan-Git** [comment]
No, gravity doesn't take sharding ddl into consideration for now. There's no coordination between different gravity processes.

But in production use cases, it's not a big problem. Commonly we just add column as drop column is not backward compatible. Gravity will

- fill in with default value if target has more column than source.
- ignore error from adding column if target column already exists.

So it won't fail on such case.

BTW, pingcap has a product called DM aiming at sync shard instances into merged one(their TiDB cluster), which pay much effort on sharding DDLs. You could take a look whether it meets ur requirement.

**Comment by louishust** [comment]
@Ryan-Git  Thanks for your reply.
As i mentioned above, 1->4->2 execute order will make the shard2 `insert(2,2)` get error which can not be ignored.

BTW, Is it easy to implement sync ddl for shard tables on gravity? Just add some plugin module in pipeline? or need modify the architecture?

**Comment by Ryan-Git** [comment]
Yes, for dropping column the error can't be ignored.

In this case, a temporary solution is adding a filter to remove column c1 from message on all shards,  and optionally remove the filter after all shards become sync. see doc [here](https://github.com/moiot/gravity/blob/master/docs/2.0/05-filters-en.md#delete-dml-column-configuration)

But for overall sharding DDL, it's quite a big story.

**Comment by Ryan-Git** [comment]
close due to inactivity. Further information available upon request.
