### ISSUE TITLE
help

### ISSUE THREAD

**Issue by wangkedba** [moiot/gravity#20]
没有同步成功，提示信息如下
[mysql] 2019/01/05 17:26:05 packets.go:36: read tcp 10.0.1.4:46838->10.0.1.5:3380: i/o timeout
[mysql] 2019/01/05 17:26:37 packets.go:36: read tcp 10.0.1.4:47064->10.0.1.5:3380: i/o timeout

**Comment by killua525** [comment]
` i/o timeout` 目测网络超时，检查一下网络？

**Comment by liuhuanHappyStudy** [comment]
@wangkedba 您好，请问有查清楚，什么原因吗？我也遇到了类似的问题：
版本信息：Gravity: v0.9.68 MySQL:8.0.11，同步源端和目标端可内网通信。
我的错误日志如下：
[mysql] 2019/11/29 17:52:11 packets.go:36: read tcp 172.20.9.143:44142->172.20.120.207:3306: i/o timeout
{"level":"warning","msg":"[binlog_checker] failed probe: invalid connection","time":"2019-11-29T17:52:11+08:00"}
[mysql] 2019/11/29 17:52:14 packets.go:36: read tcp 172.20.9.143:44176->172.20.120.207:3306: i/o timeout
{"level":"fatal","msg":"[defaultPositionCache] ticker flush failed: invalid connection\n/usr/local/go/src/github.com/moiot/gravity-0.9.68/pkg/position_repos/mysql_repo.go:170: \n/usr/local/go/src/github.com/moiot/gravity-0.9.68/pkg/position_cache/cache.go:176: ","time":"2019-11-29T17:52:14+08:00"}

**Comment by Ryan-Git** [comment]
@liuhuanHappyStudy 一般网络闪断重试下就行。

**Comment by liuhuanHappyStudy** [comment]
@Ryan-Git 好的，非常感谢！
