### ISSUE TITLE
添加分库分表功能

### ISSUE THREAD

**Issue by xuchaoyang123** [moiot/gravity#201]
您好，
我们的平台是否可以添加一个 一个实例上的 单库    拆分+迁移 到 新环境 实现分库分表，谢谢。

拆分方向

老环境                                         新环境

A库                                        A1库  T01表 数据1-20 
T01表                                     A2库  T01表 数据21-40  
数据是1-100  

使用我们的工具实现 迁移外加 拆分数据
拆分逻辑可自定义

**Comment by ming535** [comment]
你这个【拆分】是指【存量数据迁移】，【迁移】是指【增量实时同步】吗？

可以通过自定义 matcher，加上 reject filter 实现。matcher 里面实现你想要的逻辑 (1 ~ 20, 21 ~ 40 等特定逻辑)

**Comment by xuchaoyang123** [comment]
谢谢你的回复。
我对咱们的产品不太了解，不过很想研究一下。
咱们有我这个需求这块的文档嘛。我学习一下。


因为目前 我这边有一个需求是 
有一个 实例 一个库 这个库里有几个超过80G的大表。
想着在本库做水平拆分，拆分完成后，在迁移到新环境。






------------------ 原始邮件 ------------------
发件人: "Hu Ming"<notifications@github.com>;
发送时间: 2019年8月27日(星期二) 晚上7:20
收件人: "moiot/gravity"<gravity@noreply.github.com>;
抄送: "我们都一样"<920966977@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [moiot/gravity] 添加分库分表功能 (#201)




你这个【拆分】是指【存量数据迁移】，【迁移】是指【增量实时同步】吗？
 
可以通过自定义 matcher，加上 reject filter 实现。matcher 里面实现你想要的逻辑 (1 ~ 20, 21 ~ 40 等特定逻辑)

**Comment by xuchaoyang123** [comment]
谢谢你的回复。
我对咱们的产品不太了解，不过很想研究一下。
咱们有我这个需求这块的文档嘛。我学习一下。






------------------ 原始邮件 ------------------
发件人: "Hu Ming"<notifications@github.com>;
发送时间: 2019年8月27日(星期二) 晚上7:20
收件人: "moiot/gravity"<gravity@noreply.github.com>;
抄送: "我们都一样"<920966977@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [moiot/gravity] 添加分库分表功能 (#201)




你这个【拆分】是指【存量数据迁移】，【迁移】是指【增量实时同步】吗？
 
可以通过自定义 matcher，加上 reject filter 实现。matcher 里面实现你想要的逻辑 (1 ~ 20, 21 ~ 40 等特定逻辑)

**Comment by ming535** [comment]
filter 的文档在这里 https://github.com/moiot/gravity/blob/master/docs/2.0/05-filters.md

自定义 matcher 的实现步骤目前没有文档，可以先看一下示例代码  https://github.com/moiot/gravity/tree/master/pkg/matchers

**Comment by Ryan-Git** [comment]
业务是咋分库的？如果是 proxy 的话可以直接 Gravity 写 proxy，sdk 的形式没有 go 客户端的话确实有点麻烦。

**Comment by xuchaoyang123** [comment]
我这块不太懂,客户那边就是头脑一热。
我查询他们的环境 最大的表 单表最大是80G 6千万数据。
您能给点切片的建议吗。什么维度切更合适。


MySQL [(none)]> select table_name,table_rows, concat(round((data_length+index_length)/1024/1024))  data from information_schema.tables where TABLE_SCHEMA in ('ssr_prod') order by 3 ;
| tpr_send_log                            |   61102443 | 86687.08MB |





MySQL [ssr_prod]> select * from tpr_send_log limit 1\G
*************************** 1. row ***************************
           id: 14359365434540032
    send_body: {"requestCode":"ELY20190517A000007","source":"APP","points":[{"route":null,"direction":null,"speed":null,"power":null,"longitude":"116.7479731838811","latitude":"25.706082079580867","radius":"10","time":"2019-05-31 23:59:52"}]}
responce_body: {"code":"A00000","msg":"操作成功","data":null}
     send_url: https://api.ely.work/api/order/feedback/gps
  create_time: 2019-06-01 00:00:00
     order_id: NULL
       tpr_id: ELY20190517A000007
  customer_id: NULL
       result: 0
    send_type: 1
1 row in set (0.02 sec)







------------------ 原始邮件 ------------------
发件人: "Ryan-Git"<notifications@github.com>;
发送时间: 2019年8月28日(星期三) 中午11:11
收件人: "moiot/gravity"<gravity@noreply.github.com>;
抄送: "我们都一样"<920966977@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [moiot/gravity] 添加分库分表功能 (#201)




业务是咋分库的？如果是 proxy 的话可以直接 Gravity 写 proxy，sdk 的形式没有 go 客户端的话确实有点麻烦。

**Comment by Ryan-Git** [comment]
按什么维度切要看业务怎么用这个表，光看表结构（还看不见就索引。。）我也不知道呀，统计下 sql 还可行一点。
我的问题是说，分库之后业务代码怎么访问数据库呢？比如用 sharding-jdbc，还是什么 proxy，不可能呢啥也不干呀。

**Comment by xuchaoyang123** [comment]
我想着把数据库裸拆分，然后让开发人员进行实现程序调度数据库和表。
客户不同意,在使用中间件。
没这方面经验,很茫然,打扰您了。








------------------ 原始邮件 ------------------
发件人: "Ryan-Git"<notifications@github.com>;
发送时间: 2019年8月29日(星期四) 上午10:11
收件人: "moiot/gravity"<gravity@noreply.github.com>;
抄送: "我们都一样"<920966977@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [moiot/gravity] 添加分库分表功能 (#201)




按什么维度切要看业务怎么用这个表，光看表结构我也不知道呀，统计下 sql 还可行一点。
 我的问题是说，分库之后业务代码怎么访问数据库呢？比如用 sharding-jdbc，还是什么 proxy， 不可能呢啥也不干呀。

**Comment by Ryan-Git** [comment]
业务自己造轮子访问分库成本太高了，不太现实。
中间件一般不会处理数据迁移，具体迁移方案要看中间件的选型再定。

**Comment by Ryan-Git** [comment]
那先关了，有问题再开。

**Comment by xuchaoyang123** [comment]
好的，谢谢。




------------------ 原始邮件 ------------------
发件人: "Ryan-Git"<notifications@github.com>;
发送时间: 2019年8月30日(星期五) 中午11:10
收件人: "moiot/gravity"<gravity@noreply.github.com>;
抄送: "我们都一样"<920966977@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [moiot/gravity] 添加分库分表功能 (#201)




Closed #201.
