### ISSUE TITLE
match-table 支持正则表达式吗，我可以将这个配置match-table = "test_table"，改成match-table = "test_table*"?  我的目的是想把符合正则表达式的表，都映射到指定的topic 

### ISSUE THREAD

**Issue by Bruce2jiang** [moiot/gravity#203]
match-table 支持正则表达式吗，我可以将这个配置match-table = "test_table"，改成match-table = "test_table*"?  我的目的是想把符合正则表达式的表，都映射到指定的topic 

# 目标端 Kafka 路由配置
# - 必填
#
[[output.config.routes]]
match-schema = "test"
match-table = "test_table"
dml-topic = "test.test_table"

**Comment by Ryan-Git** [comment]
支持 glob，正则没支持。`test_table*` 是可以的。

**Comment by Bruce2jiang** [comment]
我们现在有这个需求，需要将多个分表(业务分库分表几百张)映射到同一个topic,如果不支持正则，有什么办法解决这个问题嘛

**Comment by Bruce2jiang** [comment]
test_table*，这种方式满足不了我们需求，期盼中

**Comment by Ryan-Git** [comment]
什么样的表名？
