### ISSUE TITLE
rds mysql->kafka   command denied to user 'drc'@'xxx' for table'slave_master_info'

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#207]
When I created rds mysql to kafka example, I get the following error:

`[binlogTailer] failed GetSchema mysql. err: Error 1142: command denied to user 'drc'@'xxx' for table'slave_master_info'\n/home/travis/gopath/src/github.com/moiot/gravity/pkg/utils/db.go:52: 
\n/home/travis/gopath/src/github.com/moiot/gravity/pkg/schema_store/utils.go:103: \n/home/travis/gopath/src/github.com/moiot/gravity/pkg/schema_store/utils.go:133: \n/home/travis/gopath/src/github.com/moiot/gravity/pkg/schema_store/utils.go:72: \n/home/travis/gopath/src/github.com/moiot/gravity/pkg/schema_store/simple_schema_store.go:43: .","pipeline":"mysql2ka","time":"2019/09/19 16:17:51.870`

How can I solve this problem? Thank you!

**Comment by Ryan-Git** [comment]
please add your conf file

**Comment by Ryan-Git** [comment]
pls attach ur conf file.
the account should have REPLICATION SLAVE and REPLICATION CLIENT privilege. see https://github.com/moiot/gravity/blob/master/docs/2.0/03-inputs.md

**Comment by zhanjianS** [comment]
I've set permissions for accounts. 
    

>  GRANT SELECT, RELOAD, LOCK TABLES, REPLICATION SLAVE, REPLICATION CLIENT, INSERT, UPDATE, DELETE ON *.* TO 'drc'@'%' IDENTIFIED BY 'xxx';

>  GRANT ALL PRIVILEGES ON _gravity.* TO 'drc'@'%' IDENTIFIED BY 'xxx';

this is my conf file.

[config.txt](https://github.com/moiot/gravity/files/3633985/config.txt)

> {
  "command": [
    "/gravity",
    "-config=/etc/gravity/config.json"
  ],
  "paused": false,
  "lastUpdate": "2019-09-20T02:38:23Z",
  "config": {
    "name": "mysql2ka",
    "version": "1.0",
    "input": {
      "type": "mysql",
      "mode": "stream",
      "config": {
        "source": {
          "host": "xxxx",
          "password": "test123",
          "port": 3306,
          "username": "drc"
        }
      }
    },
    "output": {
      "type": "async-kafka",
      "config": {
        "kafka-global-config": {
          "broker-addrs": [
            "xxxx:9092"
          ],
          "mode": "async"
        },
        "routes": [
          {
            "dml-topic": "test",
            "match-schema": "sqdataviewtest",
            "match-table": "test_tb_dept"
          }
        ]
      }
    }
  },
  "configHash": "6f8cc6954f",
  "image": "moiot/gravity:v0.9.21"
_}

**Comment by Ryan-Git** [comment]
can you execute `SHOW INDEX FROM sqdataviewtest.test_tb_dept WHERE Non_unique = 0`?

**Comment by Ryan-Git** [comment]
I found the problem according to the whole stack provided in WeChat.. please wait for a while

**Comment by Ryan-Git** [comment]
@zhanjianS pls use the latest tag (v0.9.66)

**Comment by zhanjianS** [comment]
@Ryan-Git 非常感激,  我使用了最新的的tag，还是有如下错误
`binlogTailer] unexpected err: ERROR 1236 (HY000): The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires.","pipeline":"demo1","time":"2019/09/23 18:36:54.086`

我尝试配置了
`[input.config.start-position]
 binlog-gtid = "abcd:1-123,egbws:1-234"`
还是存在错误
请问是还需要配置什么嘛？

**Comment by Ryan-Git** [comment]
@zhanjianS 回复在这里

> @Ryan-Git 非常感激, 我使用了最新的的tag，还是有如下错误
> binlogTailer] unexpected err: ERROR 1236 (HY000): The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires.","pipeline":"demo1","time":"2019/09/23 18:36:54.086
> 
> 我尝试配置了
> [input.config.start-position] binlog-gtid = "abcd:1-123,egbws:1-234"
> 还是存在错误
> 请问是还需要配置什么嘛？

因为之前同步过，这个错的意思是 gravity 在尝试从上次中断的地方继续同步，但是 binlog 已经被清理掉了。

有两个解决方法。

1. 重新同步。删除 _gravity.gravity_positions 表下 name 列与配置中 name 属性相同的记录（看日志叫 demo1 ），再启动 gravity 即可。

1. 指定开始位点，即配置`input.config.start-position`。值可以在 mysql 上执行 show master status，将结果的 gtid 写进去（也可以自己读 binlog 取任意合法位点）。示例中的 `abcd:1-123,egbws:1-234` 不是合法的 gtid，只是示意一下。

两种方式本质是一样的，都是跳过中间没有 binlog 的部分，从 MySQL 的当前位点或指定位点重新开始。不熟悉 gtid 的话可以使用第一种方式。

**Comment by zhanjianS** [comment]
非常感谢  我按照第二种方法制定了gtid  也尝试了新建了一个demo 还是出现了最开始出现错误信息，错误详情如下
`{"file":"binlog_tailer.go","level":"info","line":260,"msg":"[binlogTailer] rotate binlog to (mysql-bin.000874, 4)","pipeline":"demo1","time":"2019/09/24 15:18:36.090"}
2019/09/24 15:18:36 INFO  rotate to (mysql-bin.000875, 4)
2019/09/24 15:18:36 INFO  rotate to (mysql-bin.000875, 4)
{"file":"batch_table_scheduler.go","level":"info","line":250,"msg":"[batchScheduler.SubmitMsg] added new sliding window, key=mysqlstream, type=ctl","pipeline":"demo1","time":"2019/09/24 15:18:36.621"}
{"file":"static_sliding_window.go","level":"info","line":136,"msg":"[staticSlidingWindow] init nextItemToCommit: 1","pipeline":"demo1","time":"2019/09/24 15:18:36.621"}
{"file":"binlog_tailer.go","level":"fatal","line":311,"msg":"[binlogTailer] failed GetSchema mysql. err: Error 1142:  command denied to user 'drc'@'10.20.3.156' for table 'slave_master_info'\n/home/travis/gopath/src/github.com/moiot/gravity/pkg/utils/db.go:52: \n/home/travis/gopath/src/github.com/moiot/gravity/pkg/schema_store/utils.go:103: \n/home/travis/gopath/src/github.com/moiot/gravity/pkg/schema_store/utils.go:133: \n/home/travis/gopath/src/github.com/moiot/gravity/pkg/schema_store/utils.go:72: \n/home/travis/gopath/src/github.com/moiot/gravity/pkg/schema_store/simple_schema_store.go:43: .","pipeline":"demo1","time":"2019/09/24 15:18:36.670"}
`
ps: 这边是helm install 部署的docker服务

**Comment by Ryan-Git** [comment]
奇怪，确认用了 v0.9.66 的 docker image？要更新[部署规则](https://github.com/moiot/gravity-operator#DeploymentRules)，贴一下 helm values 的配置吧。

**Comment by zhanjianS** [comment]
不好意思 ，已经确定了，在用helm部署的时候，他们拉取的 docker image 不是最新的，更新最新docker image之后，demo已经可以跑通。
再次感谢你的帮助@Ryan-Git
