### ISSUE TITLE
Question: What's function of config `use-shading-proxy`?

### ISSUE THREAD

**Issue by ericsyh** [moiot/gravity#212]
In the [example-mysql2mysql-inc.toml](https://github.com/moiot/gravity/blob/master/docs/2.0/example-mysql2mysql-inc.toml), there is a config `use-shading-proxy`. 

After checking the doc there is no explanation of this config, so want to check the config function and how to use it ?

**Comment by Ryan-Git** [comment]
It's a legacy internal config, has been replaced by a more general one. I'll update the doc later.

The story behinds is when writing through a db proxy(such as kingshard, sharding-jdbc, vitess, etc), we could setup specific annotation to tune proxy behavior, such as selecting specific sharding instance.
