### ISSUE TITLE
mysql同步问题

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#214]
您好 请问
1、docker部署，在开启多个pipelines时，日志会出现如下错误
`Too many connections\n/home/travis/gopath/src/github.com/moiot/gravity/pkg/schema_store/utils.go:139: error show columns from `sqlretatest`.`zm_goods_entities`\n/home/travis/gopath/src/github.com/moiot/gravity/pkg/schema_store/utils.go:72: \n/home/travis/gopath/src/github.com/moiot/gravity/pkg/schema_store/simple_schema_store.go:59: .","time":"2019-09-25T15:53:59+08:00"`
这个是否做些什么限制？

2、在配置同步任务pipeline时，设置了如下的gtid，第一次是从设置的gtid开始同步，如果更新配置时，是否需要重设gtid点位，还是去除这个配置 此时的 pipeline会从后端获取对应gtid？
[input.config.start-position]
binlog-gtid = "abcd:1-123,egbws:1-234"

**Comment by Ryan-Git** [comment]
1、源端、目标端最大连接数都可以配置的，详见 [源端](https://github.com/moiot/gravity/blob/master/docs/2.0/03-inputs-en.md)，[目标端](
https://github.com/moiot/gravity/blob/master/docs/2.0/04-outputs-en.md#mysql-configuration)。json 配置的字段名、结构都是一样的，对应就好。

2、这块逻辑是这样的，gravity 会保存用户设置的起始位点和当前的位点。重启时，如果配置文件的位点与保存的起始位点相同，会从之前暂停的位置继续；如果配置的位点不为空且和保存的不同，会重新从配置的位点开始同步，忽略之前的进度。
具体到你这里，如果更新配置后是希望继续同步的话（大部分情况应该是这样），不需要更新位点也不需要去除这个配置，不动就行。如果更新配置后确实希望从特定的地方重新开始同步，那可以更新起始位点。

**Comment by zhanjianS** [comment]
非常感谢！还有两个问题想请问下
1、mysql2kafka ，这边测试是没有拿到ddl语句
 如果要获取ddl 
`[output.config]
enable-ddl = true # 当前支持 create & alter table 语句。库表名会根据路由信息调整。`
这个配置，应该在哪配置，我在下图位置配置，但是提交更改错误
![图片](https://user-images.githubusercontent.com/31116868/66544250-346b0380-eb6a-11e9-8315-deb1c7f61323.png)

2、
我在es的配置中看到如下配置
ignore-no-primary-key = false
这个是否能够用于过滤没有主键表的数据？

谢谢！

**Comment by Ryan-Git** [comment]
在 kafka 输出里目前没有发 ddl。DDL 需要全局时序，对 kafka 来说除非只有单个 partition 不然做不到。

这个配置的含义是（对 es output）碰到没主键的消息继续处理而不是中断报错。“过滤没有主键表的数据”是什么意思？

**Comment by zhanjianS** [comment]
[https://github.com/moiot/gravity/issues/215](url)
这个issue的问题，rds 的mysql 中 当没有主键的数据表进行更新时，同步任务就会停止报错
有没有办法可以过滤到这些没有主键的数据表？

**Comment by Ryan-Git** [comment]
需要手动配置一下，比如
```toml
[[filters]]
type = "reject"
[filters.config]
match-schema = "test"
match-table = ["a1", "b*"]
```
另外还是建议所有表都加主键。

**Comment by zhanjianS** [comment]
非常感谢！
