### ISSUE TITLE
 runtime error: index out of range  

### ISSUE THREAD

**Issue by selectliu** [moiot/gravity#215]
阿里云 rds同步
表结构如下无主键
REATE TABLE `pay_trade_order_extends` (
  `trade_id` int(10) unsigned DEFAULT '0' COMMENT 'xxx',
  `ext_name` varchar(50) NOT NULL DEFAULT '' COMMENT 'xx',
  `ext_value` varchar(500) NOT NULL DEFAULT '' COMMENT 'xxx',
  KEY `idx_trade_id` (`trade_id`),
  KEY `union_trade_id_name` (`trade_id`,`ext_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

gravity_positions表同步的点位如下
{"current_position":{"binlog-name":"mysql-bin.000930","binlog-pos":49856560,"binlog-gtid":"47cc8d9e-7c6e-11e9-8e40-506b4b3f16be:45-272,497bd5f9-3584-11e9-bfd4-98039b46e328:1-11685460,5b1151b5-8058-11e9-a7c6-98039b0736ac:3-82"},"start_position":{"binlog-name":"","binlog-pos":0,"binlog-gtid":"47cc8d9e-7c6e-11e9-8e40-506b4b3f16be:45-272,497bd5f9-3584-11e9-bfd4-98039b46e328:1-10793031,5b1151b5-8058-11e9-a7c6-98039b0736ac:3-82"}}

后台日志报错如下图
  
![图片](https://user-images.githubusercontent.com/7233990/66478952-1059e480-eace-11e9-88c9-f1827808d4c9.png)

下面是mysqlbinlog解析出来的那条insert 语句
#191008 13:41:54 server id 1742015502  end_log_pos 49859335 CRC32 0x76a566f7    Write_rows: table id 7701563 flags: STMT_END_F
###   @4=368 /* LONGINT meta=0 nullable=0 is_null=0 */

是因为没有主键导致的index out of range吗，而且我看同步到的点位是49856560？
49856560这个点位并不是这个sql语句,是下面这个sql，能否看下是什么原因导致的，是不是没有主键导致的。

# at 49856560
#191008 13:41:50 server id 1742015502  end_log_pos 49856640 CRC32 0x06ca09a1    Query   thread_id=8128854       exec_time=0     error_code=0
SET TIMESTAMP=1570513310.422208/*!*/;
BEGIN
/*!*/;
# at 49856640
#191008 13:41:50 server id 1742015502  end_log_pos 49856714 CRC32 0xaca0ea14    Table_map: `_gravity`.`gravity_heartbeat_v2` mapped to number 7713230
# at 49856714
#191008 13:41:50 server id 1742015502  end_log_pos 49856820 CRC32 0x57d67834    Update_rows: table id 7713230 flags: STMT_END_F
###   @4='2019-10-08 13:41:50.422208' /* DATETIME(6) meta=6 nullable=1 is_null=0 */
# at 49856820

**Comment by Ryan-Git** [comment]
rds 会在没主键的表上自己加列吗？原生 MySQL 是不会的。

**Comment by Ryan-Git** [comment]
看起来是阿里云添加的，看[这篇](https://help.aliyun.com/knowledge_detail/128324.html)，他有个 implicit_primary_key 选项默认开启。

建议还是自己加主键吧。

**Comment by selectliu** [comment]
嗯，这个之前确认过阿里云是会加主键。这个是因为加了主键导致的停止服务吗？我看停止的点位和这条sql的点位不太一样。

**Comment by Ryan-Git** [comment]
数组越界的堆栈看一下，光多一列不会挂的。
位点不是每次更新都存的，会落后一点，不然源端压力不是 double 了。

**Comment by zhanjianS** [comment]
![图片](https://user-images.githubusercontent.com/31116868/66549573-20c59a00-eb76-11e9-8e1c-d9aa0a05bc2d.png)
您好！这个是能看到的全部日志

**Comment by Ryan-Git** [comment]
还是 schema 比 binlog 少了一列导致的

**Comment by Ryan-Git** [comment]
先关了，还有问题的话再开。
