### ISSUE TITLE
关于_gravity用户权限

### ISSUE THREAD

**Issue by glkappe** [moiot/gravity#217]
该用户_gravity权限是否有更详细的划分

**Comment by Ryan-Git** [comment]
> GRANT SELECT, RELOAD, LOCK TABLES, REPLICATION SLAVE, REPLICATION CLIENT, INSERT, UPDATE, DELETE ON *.* TO '_gravity'@'%';

为了订阅，REPLICATION SLAVE, REPLICATION CLIENT 是必须的。另外需要有 information_schema 里特定表的 SELECT 权限从而查询表结构。全量模式也需要有相应表的 select 权限。insert/update/delete 主要是在目标端写入用的，但一个实例很可能既是订阅源又是写入目标（比如在双向同步中），为了简化账户配置就这样给权限了。如果比较严格的话可以考虑读和写的账户分开。

> GRANT ALL PRIVILEGES ON _gravity.* TO '_gravity'@'%';

这是内部库，用于心跳、保存位点、双向同步等，不影响业务。

**Comment by glkappe** [comment]
@Ryan-Git 清晰！
感谢回复，祝好~
