### ISSUE TITLE
有计划支持不开启gtid ，mysql到mysql 的数据同步吗

### ISSUE THREAD

**Issue by lovegengguoliang** [moiot/gravity#218]
有计划支持不开启gtid ，mysql到mysql 的数据同步吗

**Comment by Ryan-Git** [comment]
目前没有。

云厂商为了主备肯定都会开 gtid，自建的话为啥不开呢？

**Comment by lovegengguoliang** [comment]
历史原因了 ，老的环境没有开启

**Comment by vkingnew** [comment]
可以在线将传统复制升级为GTID版本，MySQL5.7+都支持的

**Comment by CrazyNash** [comment]
是什么原因不能支持非GTID实例？ 

现在gravity启动的时候会检查GTID, 没开就退出了。 为什么要加这个检查？

binlog 中的前缀/*gravity*//*pipelineName*/ 跟是否开启GTID 并没有关系。

@Ryan-Git

**Comment by Ryan-Git** [comment]
订阅 binlog 只用了 gtid，单纯是实现问题。
