### ISSUE TITLE
mysql2Kafka 输出数据 data中数据类型全为string

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#220]
您好，在进行mysql->kafka同步后，对kafka的数据进行消费打印后
发现data和old中的数据类型全为string类型

打印出来的数据
![图片](https://user-images.githubusercontent.com/31116868/67083722-3e29e200-f1ce-11e9-9f7f-98e286f64f64.png)
表结构
![图片](https://user-images.githubusercontent.com/31116868/67083306-83014900-f1cd-11e9-8000-421228acee62.png)

**Comment by Ryan-Git** [comment]
不好意思群里回答有误，是全用了字符串。原因是可以避免很多丢失精度问题，比如浮点数，长整数等等。
当然更好的策略是仔细区分所有类型，能用 json 原生类型的就用。但目前还没有实现。

**Comment by zhanjianS** [comment]
谢谢！感觉现在全是string，对后续的处理不太友好，这个有后续改造计划嘛

**Comment by Ryan-Git** [comment]
暂时还没有。
后续你们会怎么处理呢？即使用对应的类型也很麻烦，比如 int 会变成 number，但 bigint/double 就还是 string。除非把列类型也写进消息体，或者是用 protobuf。

**Comment by zhanjianS** [comment]
我这边后续打算把数据写到es和phoenix中，
之前了解过maxwell的数据输出格式跟这个比较像，它的不全是string,也没有写列类型

**Comment by Ryan-Git** [comment]
大致看了眼 maxwell 是用 jackson 序列化，没仔细找有没有定制。jackson 默认会把长整型序列化成浮点数，这样在同步的时候是会有问题的。如果定制了，那就也是字符串，即我说的第一种方案，int 变成 number，但 bigint/double 还是 string。

本质上 json 的 number 类型就是没法兼容，跟哪个框架关系不大。

**Comment by Ryan-Git** [comment]
我们有一个用 protobuf any 序列化的方案，但目前没有哪里需要就一直搁置。
有什么想法/问题再提吧，这个问题先关了。
