### ISSUE TITLE
How to set up Bidirectional data replication for MySQL 2 MySQL

### ISSUE THREAD

**Issue by CrazyNash** [moiot/gravity#221]
By running two gravity tasks? Can you show an detailed example?

By the way, can you list the limitation for bidirectional data replication? Seems it doesn't support DDL?

**Comment by Ryan-Git** [comment]
yes by running two processes. Each enables `input.ignore-bidirectional-data` and `output.sql-engine-config.tag-internal-txn`.

It supportes DDL. DDL will also be tagged to prevent endlesss repetition.

There're two major limitations（which is, by nature)

1. auto_increment primary key can't be used without change. you can either use uuid/snowflake style uid or set auto increment step on each mysql instance accordingly.

1. The same record(identified by pk/uks) shouldn't be updated on both sides at the same time. If so, the final result is unpredictable. In practice, we often leverage feature flags to dispatch the incoming traffic to a specific instance, like by user_id.

**Comment by CrazyNash** [comment]
@Ryan-Git Thank you for the quick response,

From the example doc https://github.com/moiot/gravity/blob/dc97ba7b006bab1568d4fcc8caefa47c8c7163c8/docs/2.0/example-mysql2mysql-inc.toml 

Seems 

> use-bidirection = true

 is the only one required?
 ```
[output.config.execution-engine]
use-bidirection = true
# with following two config enabled, gravity will add /*abc*/ to every statement executed, which is useful to hint db proxies
tag-internal-txn = true
sql-annotation = "abc"
```

**Comment by Ryan-Git** [comment]
not exactly. pay attention to [L19](https://github.com/moiot/gravity/blob/dc97ba7b006bab1568d4fcc8caefa47c8c7163c8/docs/2.0/example-mysql2mysql-inc.toml#L19).

```
[input.config]
ignore-bidirectional-data = true
```

We do have some rare cases that tag output(use-bidirection = true) while accept input(ignore-bidirectional-data = false), or the opposite, in a complex cascading topology. That's why there're two options instead of one.

**Comment by CrazyNash** [comment]
@Ryan-Git  Tested for several scenarios, repeated data generated when inserting data if there was no PK from a table.  

Is there any other pre-requisite except for PK?

Seems DDL is identified by /*gravity*//*pipelineName*/, how about DML? how to know it's internal traffic or external one?

**Comment by Ryan-Git** [comment]
Yes we need a primary key, otherwise each row written has to do a full table scan before insert, which is not acceptable.

Nothing more. Actually PK is also strongly recommended in native mysql replication.. so we don't regard it as a pre-requisite.

To identify internal DML manually, you need take a look at the binlog. Internal DML will be wrapped in a transaction with a insert to internal table. Here's how the actual txn looks like: 

```sql
begin;
insert into `_gravity`.`_gravity_txn_tags` (id,pipeline_name) values (123, 'abc') on duplicate key update v = v + 1, pipeline_name = 'abc';
{the actual statement};
commit;
```

External traffic won't have such structure.

**Comment by CrazyNash** [comment]
@Ryan-Git Sorry I didn't make it clear. The internal traffic I mean the potential circle customer traffic(not the metadata traffic for _gravity). 

Let's talk with an example, from testing I saw the following circle:

```
A 执行 insert/update， 产生 binlog.
           A-->B Gravity 任务收到这条 binlog, 改为replace into发送给B.
B 执行replace into， 产生 binlog.
           B-->A Gravity 任务收到这条 binlog, 改为replace into发送给A。
A 执行 replace into, 因为数据没有变化， 不会产生binlog.  
```

There are duplicated traffic for A, is my understanding correct here?

And also hit a failure:

```
A: create table
A: insert into 
A: drop table
```
B-->A Gravity  insert failed for target table doesn't exist. 

Is this a limitation? any improvement?

**Comment by Ryan-Git** [comment]
没看懂问题。

开了双向同步之后 replace 会包在事务里（事务里的另一个语句是写`_gravity_txn_tags` 表），识别之后就不会继续同步了。

第二个，B 重启之后就正常了。或者 insert 跟 drop 中间间隔一段时间，B 执行完 insert 再看到 drop 也会处理内部状态。

**Comment by CrazyNash** [comment]
@Ryan-Git 


> 开了双向同步之后 replace 会包在事务里（事务里的另一个语句是写_gravity_txn_tags 表），识别之后就不会继续同步了。

这里是怎么识别的？

```
A 执行 insert/update， 产生 binlog.
           A-->B Gravity 任务收到这条 binlog, 改为replace into发送给B.
B 执行replace into， 产生 binlog.
           B-->A Gravity 任务收到这条 binlog, 改为replace into发送给A。
A 执行 replace into, 因为数据没有变化， 不会产生binlog.  
```
也就说这里的第三条有个尝试的动作，但没有真正执行？

**Comment by Ryan-Git** [comment]
举个例子吧。比如用户在 A 执行 insert into a(id) values (1);
A -> B 的 gravity 收到后会在 B 执行下面这个事务
```sql
begin;
insert into `_gravity`.`_gravity_txn_tags` (id,pipeline_name) values (123, 'abc') on duplicate key update v = v + 1, pipeline_name = 'abc';
replace into a(id) values (1);
commit;
```

B -> A 的 gravity 收到这个事务后会识别对 `_gravity_txn_tags` 表的操作，忽略整个事务，也就不会再在 A 执行 replace into a(id) values (1);

**Comment by CrazyNash** [comment]
@Ryan-Git 明白了， 非常感谢。
