### ISSUE TITLE
增量同步报错 primary key nil, pkName

### ISSUE THREAD

**Issue by zeusYi** [moiot/gravity#223]
1、目标库表情况
mysql> select count(*) from sms_201910 where id>=133204362;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)

2、启动同步进程

[root@ip-172-33-2-46 gravity]# ./main -config=mysql2mysql_full.toml
INFO[0000] xxhash backend: GoUnsafe                     
{"level":"info","msg":"Welcome to gravity.","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"Release Version: None","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"Git Commit Hash: None","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"Git Branch: None","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"UTC Build Time: None","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"[output-mysql] Using mysql-replace-engine","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"[batchScheduler] {NrWorker:1 MaxBatchPerWorker:2 QueueSize:1024 SlidingWindowSize:1024 NrRetries:0 RetrySleepString: HealthyThreshold:0 RetrySleep:1s}","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"DSN is microl:passwd@tcp(172.33.4.229:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"DSN is microl:passwd@tcp(172.33.4.229:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"DSN is microl:passwd@tcp(172.33.4.229:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"DSN is microl:passwd@tcp(172.33.4.229:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"DSN is mysqlroot:passwd@tcp(127.0.0.1:6001)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"DSN is mysqlroot:passwd@tcp(127.0.0.1:6001)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"[Server] start input","time":"2019-10-31T06:17:47Z"}
{"file":"two_stage_input.go","level":"info","line":84,"msg":"[TwoStageInputPlugin.Start] with inc","pipeline":"gravity_full_mysql_sms","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"DSN is microl:passwd@tcp(172.33.4.229:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"DSN is microl:passwd@tcp(172.33.4.229:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"[binlog_checker] start","time":"2019-10-31T06:17:47Z"}
[2019/10/31 06:17:47] [info] binlogsyncer.go:141 create BinlogSyncer with config {5302005 mysql 172.33.4.229 3306 microl    false false <nil> true UTC false 0 0s 0s 0 false 0}
{"level":"info","msg":"[binlogTailer] start","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"[binlogTailer] getBinlogStreamer gtid: 838fda78-dad4-11e9-8ae0-029c6716ccfa:1-811472819,8d0d1b72-9bb3-11e9-8934-0a4d6b283f70:1-1260212552,ea784db2-ee74-11e9-8647-0abb3d201cf8:1-1440550,3d9bc8be-075e-11e9-82a4-02e09b2a90ee:1-766096890","time":"2019-10-31T06:17:47Z"}
[2019/10/31 06:17:47] [info] binlogsyncer.go:380 begin to sync binlog from GTID set 838fda78-dad4-11e9-8ae0-029c6716ccfa:1-811472819,8d0d1b72-9bb3-11e9-8934-0a4d6b283f70:1-1260212552,ea784db2-ee74-11e9-8647-0abb3d201cf8:1-1440550,3d9bc8be-075e-11e9-82a4-02e09b2a90ee:1-766096890
[2019/10/31 06:17:47] [info] binlogsyncer.go:211 register slave for master server 172.33.4.229:3306
{"level":"info","msg":"[Server] started","time":"2019-10-31T06:17:47Z"}
[2019/10/31 06:17:47] [info] binlogsyncer.go:731 rotate to (mysql-bin-changelog.004572, 4)
{"level":"info","msg":"[binlogTailer] skip rotate event: source binlog Name mysql-bin-changelog.004572, source binlog Pos: 4; store Name: mysql-bin-changelog.004572, store Pos: 26214919","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"[batchScheduler.SubmitMsg] added new sliding window, key=mysqlstream, type=dml","time":"2019-10-31T06:17:47Z"}
{"level":"info","msg":"[staticSlidingWindow] init nextItemToCommit: core.Msg{ mysqlstream-1 dml insert map[id:133204362] }","time":"2019-10-31T06:17:47Z"}
{"level":"fatal","msg":"[binlogTailer] failed to genUpdateJobs /root/go/src/github.com/moiot/gravity/pkg/mysql/utils.go:38: primary key nil, pkName: id\n/root/go/src/github.com/moiot/gravity/pkg/inputs/mysqlstream/msg.go:157: ","time":"2019-10-31T06:17:48Z"}

3、再查目标库的情况
mysql> select count(*) from sms_201910 where id>=133204362;
+----------+
| count(*) |
+----------+
|      464 |
+----------+
1 row in set (0.00 sec)

**Comment by Ryan-Git** [comment]
怎么复现？

**Comment by Ryan-Git** [comment]
rewrite_plugin 的存储过程导致 binlog 里有不是 full 格式的日志（本例中缺少主键）。目前的解决方案是在解析消息前就跳过没有路由的 rows_event

binlog 如下，@1 是主键 id 列：

>  UPDATE `query_rewrite`.`rewrite_rules`
>  WHERE
>    @2='SELECT T0.`id`, T0.`user_account_id`, T0.`order_id`, T0.`amount`, T0.`razorpay_order_id`, T0.`payment_id`, T0.`status`, T0.`callback_json`, T0.`check_time`, T0.`ctime`, T0.`utime` FROM `razorpay_order` T0 WHERE T0.`id` > ? AND T0.`status` = ? AND T0.`check_time` < ? AND T0.`check_time` > ? ORDER BY T0.`id` ASC LIMIT 100'
>    @3='microloan'
>    @4='SELECT T0.`id`, T0.`user_account_id`, T0.`order_id`, T0.`amount`, T0.`razorpay_order_id`, T0.`payment_id`, T0.`status`, T0.`callback_json`, T0.`check_time`, T0.`ctime`, T0.`utime` FROM `razorpay_order`  T0 force index(idx_status_check_time) WHERE T0.`id` > ? AND T0.`status` = ? AND T0.`check_time` < ? AND T0.`check_time` > ? ORDER BY T0.`id` ASC LIMIT 100'
>    @5=1
>    @6=NULL
>  SET
>    @5=1
>    @6=NULL
>    @7='6723b58153dc3278d394a57b46927351'
>    @8='select `T0`.`id`,`T0`.`user_account_id`,`T0`.`order_id`,`T0`.`amount`,`T0`.`razorpay_order_id`,`T0`.'

**Comment by Ryan-Git** [comment]
closes by #224
