### ISSUE TITLE
Drop table support

### ISSUE THREAD

**Issue by CrazyNash** [moiot/gravity#225]
Currently drop table action loops from MySQL bidirectional replication, while it's a quite common request.

**Comment by Ryan-Git** [comment]
what do you mean by `loops`?

drop is executed in the same way as other DDLs that would be ignored in bidirectional replication.

**Comment by CrazyNash** [comment]
> what do you mean by `loops`?
> 
> drop is executed in the same way as other DDLs that would be ignored in bidirectional replication.

数据库里的table 确实被同步删除了， 但是日志里全是重复的drop table， 还在不断增长。其它DDL都是正常的。
```
{"level":"info","msg":"QueryEvent: database: nash, sql: DROP TABLE IF EXISTS `uk12` /* generated by server */","time":"2019-11-08T14:45:55+08:00"}
...
{"level":"info","msg":"QueryEvent: database: nash, sql: DROP TABLE IF EXISTS `uk12` /* generated by server */","time":"2019-11-08T14:45:55+08:00"}
...
{"level":"debug","msg":"[binlogTailer] do not ignore traffic: hasInternalTxnTag false, cfg.Ignore true, msgTxnBufferLen: 1","time":"2019-11-08T14:45:55+08:00"}
{"level":"info","msg":"QueryEvent: database: nash, sql: DROP TABLE IF EXISTS `uk12` /* generated by server */","time":"2019-11-08T14:45:55+08:00"}
...
```

**Comment by Ryan-Git** [comment]
我看下

**Comment by Ryan-Git** [comment]
mysql 处理 drop 确实有些不一样，我看下。

**Comment by Ryan-Git** [comment]
这是一个已知问题 (https://bugs.mysql.com/bug.php?id=87852)
我想想怎么处理

**Comment by CrazyNash** [comment]
@Ryan-Git 这个什么时候能发一个版本？
