### ISSUE TITLE
建议增加HeartbeatPeriod选项

### ISSUE THREAD

**Issue by zhanglei** [moiot/gravity#226]
gravity在连接master时，会出现
![图片](https://user-images.githubusercontent.com/241508/68639128-8ffc2880-053e-11ea-92bc-685aa2fa24d8.png)
该binlog同步链接断开
在gravity端，查看tcp链接进程正常
![IMG20191112112304](https://user-images.githubusercontent.com/241508/68639243-e4070d00-053e-11ea-9f73-d7e87809551f.png)

master端上的tcp链接此时已断开，经分析源码后，在建立复制时增加HeartbeatPeriod参数可解决此问题

若master端无binlog产生时，会定时发送数据包到gravity，以确认slave是否正常
![IMG20191112112531](https://user-images.githubusercontent.com/241508/68639321-27fa1200-053f-11ea-83cb-f67e6500d8d0.png)

**Comment by Ryan-Git** [comment]
这两天会有pr。

补充一下，正常部署不会有这个问题，gravity 自身会发心跳（每秒）写源库，然后就能收到心跳的 binlog，保证全链路的畅通（我们在老版本的 go 上还遇到过进程假死）。健康检查接口(/healthz)就是以这个原理设置的。

这边的特殊情况是权限原因导致用户特意没写心跳，再加上更新比较少，就需要主从同步的那个连接额外维持心跳，实际就是 mysql 的 `MASTER_HEARTBEAT_PERIOD` 功能。但要注意的是这样的部署下健康检查和一部分监控指标就不生效了。
