### ISSUE TITLE
rename table 问题

### ISSUE THREAD

**Issue by glkappe** [moiot/gravity#228]
@Ryan-Git 您好，我升级了最新版本，
执行（git clone https://github.com/moiot/gravity.git cd gravity && make go mod tidy）
重新启动了gravity,除了这些还需要做什么吗

[root@ser4-45 bin]# ./gravity -V
Release Version (gravity): 0.0.1+git.341e94a
Git Commit Hash: 341e94a
Git Branch: master
UTC Build Time: 2019-11-13 07:40:44
[root@ser4-45 bin]#

我的配置文件:
[[output.config.routes]]
match-schema = "coon_a"
match-table = ["a*"]

下图是我测试rename table的截图:
 
![image](https://user-images.githubusercontent.com/21033020/68748804-0e88c100-0638-11ea-96a9-9d5ea95ca346.png)

**Comment by glkappe** [comment]
灰常感谢，现在通过
`[[output.config.routes]]  match-table-regex`参数，可以精确到表支持osc了。

**Comment by Ryan-Git** [comment]
@glkappe 可以写一下具体是怎么用的？后面的同学也可以参考一下。
