### ISSUE TITLE
gravity启动日志问题

### ISSUE THREAD

**Issue by glkappe** [moiot/gravity#233]
问题：
     gravity升级到最新master后（#230更新之后），每次重启gravity日志都会打印如下图所示的东西。为了防止这个我设置了
`[[input.config.ignore-tables]]
schema = "_gravity"
table = "*"
`
但是并没有效果，请问，需要该如何解决这个呢，或者为啥会出现这个现象呢？
（虽然不影响复制吧。）

![image](https://user-images.githubusercontent.com/21033020/69316186-41a00580-0c73-11ea-85d9-af3bad975e3e.png)

**Comment by Ryan-Git** [comment]
启动的时候会确保内部表已经创建，之前一个提前忽略没有路由消息的pr忘记处理ddl了。
没啥大影响，晚点弄一下。

**Comment by glkappe** [comment]
了解，感谢回复~~
