### ISSUE TITLE
同步的表结构主从不一致

### ISSUE THREAD

**Issue by canxuegigi** [moiot/gravity#239]
源库：PXC集群，5.7.28
从库：percona的mysql，5.7.28

源库的建表语句如下：
CREATE TABLE `user_info__aa` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `create_time` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `modify_time` datetime(3) DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1694029 DEFAULT CHARSET=utf8

gravity日志中获取的建表语句如下：时间字段的默认值中的CURRENT_TIMESTAMP函数里面的数字没有获取到
CREATE TABLE `user_info__aa` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `create_time` datetime(3) DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
  `modify_time` datetime(3) DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP() COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1694029 DEFAULT CHARSET=utf8

从库执行报错：rror 1067: Invalid default value for 'create_time'

**Comment by Ryan-Git** [comment]
是一个已知问题 #59
我更新一下 parser 看看
