### ISSUE TITLE
是否支持源端到目的端主机级别的复制

### ISSUE THREAD

**Issue by selectliu** [moiot/gravity#242]
是否支持源端到目的端主机级别的复制，一次复制多个库？例如如下图的配置，源端新创建一个db之后，目标端能够自动复制过去。

![图片](https://user-images.githubusercontent.com/7233990/69782290-8683e900-11eb-11ea-9605-935d1f4109b9.png)

**Comment by Ryan-Git** [comment]
应该是支持的。报什么错？

**Comment by selectliu** [comment]
我配置的replication模式。提示我表不存在。报错如下图，看起来像是增量模式
![图片](https://user-images.githubusercontent.com/7233990/69790690-e2576d80-11fd-11ea-8e0b-c236c4e57af0.png)

**Comment by Ryan-Git** [comment]
是不是之前同步过？清一下位点或者改个名字
k8s 上的对吧，admin 上先 pause，再 reset，再 start
因为一直在报错退出所以得这样搞，如果是正常同步状态直接 reset 就行

**Comment by selectliu** [comment]
之前同步过，我把  gravity_heartbeat_v2 gravity_positions 表的数据都清理掉了，重新同步还是报这个错

**Comment by Ryan-Git** [comment]
删的时候暂停了吗？没暂停的话没用

**Comment by selectliu** [comment]
![图片](https://user-images.githubusercontent.com/7233990/69798286-0457ec80-120c-11ea-8acd-62d8805785ed.png)
暂停了。pause的时候不能reset，按钮是灰色的

**Comment by Ryan-Git** [comment]
gravity-admin:v0.2.1
是手动暂停，然后清理数据库，再开始，还是这个错？
ddl 开了吗？replication 要开了 ddl 才会建表
配置文件贴一下吧

**Comment by selectliu** [comment]
是手动暂停，然后清理数据，再开始的，试了很多遍。按照这个步骤，如果我只同步一个库的话没有问题。目标端是tidb

{
  "command": [
    "/gravity",
    "-config=/etc/gravity/config.json"
  ],
  "paused": true,
  "lastUpdate": "2019-11-28T10:25:04Z",
  "config": {
    "name": "my57ro2-tidb",
    "version": "1.0",
    "input": {
      "type": "mysql",
      "mode": "replication",
      "config": {
        "batch-per-second-limit": 10,
        "nr-scanner": 10,
        "source": {
          "host": "xxxxx",
          "password": "xxxxxx",
          "port": 3306,
          "username": "gravity"
        },
        "table-configs": [
          {
            "schema": "*",
            "table": "*"
          }
        ],
        "table-scan-batch": 1000
      }
    },
    "filters": [
      {
        "type": "reject",
        "config": {
          "match-schema": "_*",
          "match-table": "*"
        }
      }
    ],
    "output": {
      "type": "mysql",
      "config": {
        "enable-ddl": true,
        "routes": [
          {
            "match-schema": "*",
            "match-table": "*",
            "target-schema": "*",
            "target-table": "*"
          }
        ],
        "target": {
          "host": "xxxxxx",
          "password": "xxxxx",
          "port": 4000,
          "username": "gravity"
        }
      }
    },
    "scheduler": {
      "type": "batch-table-scheduler",
      "config": {
        "batch-size": 20,
        "nr-worker": 10,
        "queue-size": 1024,
        "sliding-window-size": 10240
      }
    }
  },
  "configHash": "6c4b5d654d",
  "image": "registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.68-debug"
}

**Comment by selectliu** [comment]
![图片](https://user-images.githubusercontent.com/7233990/69799309-ff943800-120d-11ea-88f6-27327fb0fed3.png)

**Comment by Ryan-Git** [comment]
发一下清理之后第一次挂的日志吧
table configs 里是啥？整个删了吧

**Comment by Ryan-Git** [comment]
为啥有个空的`table-configs`？

**Comment by selectliu** [comment]
不是空的，是 * 号，copy过来的时候 git给隐掉了。
![image](https://user-images.githubusercontent.com/7233990/69801049-6b2bd480-1211-11ea-840a-de975cd08073.png)
![image](https://user-images.githubusercontent.com/7233990/69801082-767f0000-1211-11ea-946d-b0d3f93764ba.png)
![image](https://user-images.githubusercontent.com/7233990/69801142-90b8de00-1211-11ea-8111-5315aaebfc4c.png)
![image](https://user-images.githubusercontent.com/7233990/69801165-9d3d3680-1211-11ea-8c78-5e4e6abb8429.png)
![image](https://user-images.githubusercontent.com/7233990/69801184-a9c18f00-1211-11ea-9f61-558257244848.png)
![image](https://user-images.githubusercontent.com/7233990/69801244-c231a980-1211-11ea-88dd-b88d1f18684f.png)
麻烦看下，谢谢

**Comment by Ryan-Git** [comment]
不要*，table config 里的 schema 不支持glob。
table-configs 整个删了吧，会根据路由决定同步哪些表。

**Comment by selectliu** [comment]
谢谢，测试通过了，非常感谢
