### ISSUE TITLE
GetEncodedPersistentPosition 获取不到值

### ISSUE THREAD

**Issue by recall704** [moiot/gravity#243]
![image](https://user-images.githubusercontent.com/7451408/70044933-35666180-15fe-11ea-847a-3f3be81bf145.png)

请教下 Get 和 GetEncodedPersistentPosition 有什么不同？
我使用 GetEncodedPersistentPosition 获取不到 Value 值，而使用 Get 可以，数据库中也有数据。

---------

1. 数据库类型：
     mysql -> mysql （5.7.25）
2. 迁移类型
    增量

**Comment by recall704** [comment]
https://github.com/moiot/gravity/blob/master/pkg/position_cache/cache.go#L21

**Comment by Ryan-Git** [comment]
照理没啥不同，怎么复现？

**Comment by recall704** [comment]
1. startPosition 都为空
2. 每次同步前都清理 _gravity 中的数据

基本能复现

**Comment by Ryan-Git** [comment]
是这样的，保存位点是只更新内存，然后有个goroutine定期去实际保存到介质里。更新内存的时候是不序列化位点的，也就是字符串 Value 是空的，pos 对象是有值的，只有实际保存（看Flush方法）的时候才会去序列化（实际保存时候无论如何都要序列化的）。

这样优化是因为有时候位点是很大的。比如全量模式要记录每个表/分块的最大最小和当前主键值，分库分表同步上千个表很常见，如果每个事务都序列化一次位点开销也很大。

可能函数名没有很好地体现这一点，我们考虑改个名字。

**Comment by recall704** [comment]
好的，谢谢。
