### ISSUE TITLE
rds 同步到tidb 加索引报错

### ISSUE THREAD

**Issue by selectliu** [moiot/gravity#245]
rds增加索引，同步到tidb后报错，目标其实是没有这个索引的。不断的pause resume，最后也成功了，但是中间不停的报错
rds的命令如下
ALTER TABLE wm_orders ADD INDEX idx_phone_created(linkman_phone,created_at),DROP INDEX idx_receipt_created;

**Comment by selectliu** [comment]
_container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.610518527Z    content: {"level":"info","msg":"[binlogTailer] skip rotate event: source binlog Name mysql-bin.000837, source binlog Pos: 4; store Name: mysql-bin.000837, store Pos: 196012278","time":"2019-12-04T23:35:04+08:00"}
--
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stdout    _time_: 2019-12-04T15:35:04.610480888Z    content: [2019/12/04 23:35:04] [info] binlogsyncer.go:731 rotate to (mysql-bin.000837, 4)
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.608038135Z    content: {"level":"info","msg":"[Server] started","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stdout    _time_: 2019-12-04T15:35:04.580954194Z    content: [2019/12/04 23:35:04] [info] binlogsyncer.go:211 register slave for master server canyin.mysql.db.qmai.cn:3306
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stdout    _time_: 2019-12-04T15:35:04.58094553Z    content: [2019/12/04 23:35:04] [info] binlogsyncer.go:380 begin to sync binlog from GTID set afd56aa9-d38b-11e9-8039-b8599f2fcef0:1-267650708,af88898c-d38b-11e9-9a09-506b4b1d70de:1-110045141
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.580867835Z    content: {"level":"info","msg":"[binlogTailer] getBinlogStreamer gtid: afd56aa9-d38b-11e9-8039-b8599f2fcef0:1-267650708,af88898c-d38b-11e9-9a09-506b4b1d70de:1-110045141","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.573330152Z    content: {"level":"info","msg":"[binlogTailer] start","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stdout    _time_: 2019-12-04T15:35:04.573253571Z    content: [2019/12/04 23:35:04] [info] binlogsyncer.go:141 create BinlogSyncer with config {4262951 mysql canyin.mysql.db.qmai.cn 3306 gravity false false true UTC false 0 0s 0s 0 false 0}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.564307132Z    content: {"level":"info","msg":"[binlog_checker] start","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.547641522Z    content: {"level":"info","msg":"DSN is gravity:graHt#88@tcp(canyin.mysql.db.qmai.cn:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.531244143Z    content: {"level":"info","msg":"DSN is gravity:graHt#88@tcp(canyin.mysql.db.qmai.cn:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.531239469Z    content: {"file":"two_stage_input.go","level":"info","line":84,"msg":"[TwoStageInputPlugin.Start] with inc","pipeline":"takeout-tidb","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.53122292Z    content: {"level":"info","msg":"[Server] start input","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.508793363Z    content: {"level":"info","msg":"DSN is tidb:#fg#jk$bn@tcp(td01.tidb.db.qmai.cn:4000)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.491526829Z    content: {"level":"info","msg":"DSN is tidb:#fg#jk$bn@tcp(td01.tidb.db.qmai.cn:4000)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.471154624Z    content: {"level":"info","msg":"DSN is gravity:graHt#88@tcp(canyin.mysql.db.qmai.cn:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.4419563Z    content: {"level":"info","msg":"DSN is gravity:graHt#88@tcp(canyin.mysql.db.qmai.cn:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.425142183Z    content: {"level":"info","msg":"DSN is gravity:graHt#88@tcp(canyin.mysql.db.qmai.cn:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.395932666Z    content: {"level":"info","msg":"DSN is gravity:graHt#88@tcp(canyin.mysql.db.qmai.cn:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.395752729Z    content: {"level":"info","msg":"[batchScheduler] {NrWorker:100 MaxBatchPerWorker:40 QueueSize:1024 SlidingWindowSize:10240 NrRetries:0 RetrySleepString: HealthyThreshold:0 RetrySleep:1s}","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.395747835Z    content: {"level":"info","msg":"[output-mysql] Using mysql-replace-engine","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.395485605Z    content: {"level":"info","msg":"UTC Build Time: 2019-10-21 02:10:13","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.39548263Z    content: {"level":"info","msg":"Git Branch: HEAD","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.395479444Z    content: {"level":"info","msg":"Git Commit Hash: bbe2df41f71d9a5d7a471d484eac25232c616c92","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.395474989Z    content: {"level":"info","msg":"Release Version: 0.0.1+git.bbe2df4","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.395391797Z    content: {"level":"info","msg":"Welcome to gravity.","time":"2019-12-04T23:35:04+08:00"}
Time: 2019-12-04 23:35:06Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:04.395343333Z    content: time="2019-12-04T23:35:04+08:00" level=info msg="xxhash backend: GoUnsafe"
Time: 2019-12-04 23:35:03Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:03.371874701Z    content: {"file":"mysql.go","level":"fatal","line":309,"msg":"[output-mysql] error exec ddl: alter table `sqltakeout`.`wm_orders` drop index `idx_receipt_created`. err:Error 1091: index idx_receipt_created doesn't exist","pipeline":"takeout-tidb","time":"2019-12-04T23:35:03+08:00"}
Time: 2019-12-04 23:35:03Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:03.362853218Z    content: {"level":"error","msg":"[output-mysql] ignore duplicate column or index. ddl: alter table `sqltakeout`.`wm_orders` add index `idx_phone_created`(`linkman_phone`, `created_at`). err: Error 1061: index already exist idx_phone_created","time":"2019-12-04T23:35:03+08:00"}
Time: 2019-12-04 23:35:03Source: 172.22.5.2 | _container_ip_: 172.22.5.116    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: a04d4931-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:35:03.353467962Z    content: {"level":"info","msg":"QueryEvent: database: sqltakeout, sql: ALTER TABLE wm_orders ADD INDEX idx_phone_created(linkman_phone,created_at),drop index idx_receipt_created","time":"2019-12-04T23:35:03+08:00"}
Time: 2019-12-04 23:36:10Source: 172.22.5.2 | _container_ip_: 172.22.5.117    _container_name_: gravity    _image_name_: registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.67    _namespace_: gravity    _pod_name_: takeout-tidb-0    _pod_uid_: c410d3a9-16ab-11ea-938f-62b3ac7d916f    _source_: stderr    _time_: 2019-12-04T15:36:10.085914098Z    content: {"level":"info","msg":"[staticSlidingWindow] init nextItemToCommit: core.Msg{ mysqlstream-1 ctl }","time":"2019-12-04T23:36:10+08:00"}

**Comment by Ryan-Git** [comment]
到 tidb 会被拆成两条 DDL 执行，第二条 drop 需要等第一个加索引完成后才能执行，报错连接超时，后续报错重复执行的话是正常的。
