### ISSUE TITLE
Architecture picture can't be displayed  

### ISSUE THREAD

**Issue by siddontang** [moiot/gravity#249]
![image](https://user-images.githubusercontent.com/1080370/71301437-dc5a4400-23d9-11ea-956e-426223fcbc28.png)

**Comment by Ryan-Git** [comment]
I'm ok with it. The content(`<img src="/moiot/gravity/raw/master/docs/2.0/product.png" alt="2.0 Product" style="max-width:100%;">`) seems all right. 

@ming-relax what about you?

**Comment by xialuo1990** [comment]
is not Ok 
![image](https://user-images.githubusercontent.com/26832363/71474601-3c584c80-2817-11ea-9a0a-92f74998a3d3.png)

**Comment by Ryan-Git** [comment]
It seems proxy is needed for raw picture, build status and user avatar etc..
