### ISSUE TITLE
[binlog_checker] too many gravity here: 17

### ISSUE THREAD

**Issue by 1454513232** [moiot/gravity#250]
mysql版本: 8.0.17
gravity版本: 0.9.69
问题：同一台机器启动16个gravity进程后，再启动第17个进程时报错：
{"level":"info","msg":"[binlog_checker] start","time":"2019-12-23T11:16:30+08:00"}
{"level":"fatal","msg":"[binlog_checker] too many gravity here: 17","time":"2019-12-23T11:16:30+08:00"}

请问gravity是有进程数量限制吗？

**Comment by 1454513232** [comment]
/usr/local/go/src/github.com/moiot/gravity/pkg/config/limits.go
MaxNrGravity   = 16
看配置是有16的进程数限制，进程过多会有很大的影响？

**Comment by Ryan-Git** [comment]
不是进程数量限制，是连接同一个 MySQL 实例的 gravity 个数限制。slave 太多怕影响性能，所以设了这个。
为啥要开这么多呢？

**Comment by 1454513232** [comment]
嗯谢谢您的及时回复，刚刚测试了一下，gravity的确对读取同一个mysql实例有数量的限制，那我就合并进程或者单独mysql从库专做gravity同步吧,监控下看看性能影响如何

**Comment by Ryan-Git** [comment]
恩，主要是担心影响主库。我们自己一般一个实例就一个 gravity 进程，最多每个库一个。具体多少会有明显影响看环境了。

**Comment by 1454513232** [comment]
在合并进程时候，又遇到一些困惑，有两个场景
1.同个库多个表可以同步到相同目标库的多个表，比如udp库的udp_lite_user，udp_org同步到jf库的udp_lite_user，udp_org
# 路由规则的定义
[[output.config.routes]]
match-schema = "udp"
match-table = "udp_lite_user"
target-schema = "jf"
target-table = "udp_lite_user"

[[output.config.routes]]
match-schema = "udp"
match-table = "udp_org"
target-schema = "jf"
target-table = "udp_org"

2.但是不能同步到多个目标库，比如udp库的udp_lite_user同步到dlc，file，kng库的udp_lite_user表
# 路由规则的定义
# dlc
[[output.config.routes]]
match-schema = "udp"
match-table = "udp_lite_user"
target-schema = "dlc"
target-table = "udp_lite_user"

#file
[[output.config.routes]]
match-schema = "udp"
match-table = "udp_lite_user"
target-schema = "file"
target-table = "udp_lite_user"

#kng
[[output.config.routes]]
match-schema = "udp"
match-table = "udp_lite_user"
target-schema = "kng"
target-table = "udp_lite_user"

只能第一个dlc库能成功同步，可能我的配置有问题，但是没找到对应的匹配规则

**Comment by Ryan-Git** [comment]
目前没有支持一个数据写多份，找到一个匹配的路由就执行了。

**Comment by 1454513232** [comment]
ok,明白了，谢谢您，这个匹配规则和tidb的syncer的匹配规则有点相似，不过还是蛮方便的，同步速度，数据冲突转换比ogg要好，我再进一步测试吧

**Comment by 1454513232** [comment]
还是想请问下
{"level":"fatal","msg":"[binlog_checker] too many gravity here: 17","time":"2019-12-23T11:16:30+08:00"}
这个进程限制，我调整了
/usr/local/go/src/github.com/moiot/gravity/pkg/config/limits.go
MaxNrGravity = 20
但是还是只能16个进程数，还需要修改哪里才能突破这个16限制呢

**Comment by Ryan-Git** [comment]
是不是没有重新编译部署新版本，这个代码应该是一目了然的。。
```go
if nrGravity > config.MaxNrGravity {
	log.Fatalf("[binlog_checker] too many gravity here: %v", nrGravity)
}
```

**Comment by 1454513232** [comment]
改了参数没有重新编译，那我重新make下吧，谢谢

**Comment by 1454513232** [comment]
我修改了我尝试了
/usr/local/go/src/github.com/moiot/gravity/pkg/config/limits.go
MaxNrGravity = 20
重新make之后，还是有16的限制，然后我直接改
if nrGravity > 20
重新make,仍然会有16的限制，难道我改错文件了

**Comment by Ryan-Git** [comment]
是怎么部署的？跑的是重新编译出的文件吗？不然把`config.MaxNrGravity`也打印一下。
是这个文件。

**Comment by 1454513232** [comment]
我是使用二进制包安装的
# tar -zxvf gravity-0.9.69.tar.gz -C /usr/local/go/src/github.com/moiot/
# cd /usr/local/go/src/github.com/moiot
# mv gravity-0.9.69 gravity
# cd gravity/
# make
然后我重新make，重新生成了gravity执行文件，仍然没有生效
if nrGravity > config.MaxNrGravity这个判断，好像就是去读取
/usr/local/go/src/github.com/moiot/gravity/pkg/config/limits.go
MaxNrGravity = 20

**Comment by 1454513232** [comment]
我是使用二进制包安装的
tar -zxvf gravity-0.9.69.tar.gz -C /usr/local/go/src/github.com/moiot/
cd /usr/local/go/src/github.com/moiot
mv gravity-0.9.69 gravity
cd gravity/
make
然后我重新make，重新生成了gravity执行文件，仍然没有生效
if nrGravity > config.MaxNrGravity这个判断，好像就是去读取
/usr/local/go/src/github.com/moiot/gravity/pkg/config/limits.go
MaxNrGravity = 20
这个地方的设置吧，另外不好意思，不知道咋打印出config.MaxNrGravity的值

**Comment by Ryan-Git** [comment]
```go
log.Fatalf("[binlog_checker] too many gravity here: %v, expected %v", nrGravity, config.MaxNrGravity)
```

**Comment by 1454513232** [comment]
修改了pkg/inputs/helper/binlog_checker/checker.go
[root@xuanxing-mysql-dev02 gravity]# pwd
/usr/local/go/src/github.com/moiot/gravity
重新编译生成gravity执行文件
[root@xuanxing-mysql-dev02 gravity]# make
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
go build -ldflags '-X "github.com/moiot/gravity/pkg/utils.Version=0.0.1+git." -X "github.com/moiot/gravity/pkg/utils.BuildTS=2020-03-11 08:40:37" -X "github.com/moiot/gravity/pkg/utils.GitHash=" -X "github.com/moiot/gravity/pkg/utils.GitBranch="' -o bin/gravity cmd/gravity/main.go
#go build -ldflags '-X "github.com/moiot/gravity/pkg/utils.Version=0.0.1+git." -X "github.com/moiot/gravity/pkg/utils.BuildTS=2020-03-11 08:40:37" -X "github.com/moiot/gravity/pkg/utils.GitHash=" -X "github.com/moiot/gravity/pkg/utils.GitBranch="' -o bin/padder cmd/padder/main.go
执行同步后
{"level":"info","msg":"[binlog_checker] start","time":"2020-03-11T16:42:19+08:00"}
{"level":"fatal","msg":"[binlog_checker] too many gravity here: 17","time":"2020-03-11T16:42:19+08:00"}
感觉修改的配置文件也没有生效，难道是我编译的有问题，奇怪

**Comment by Ryan-Git** [comment]
这个`fatal`看着有点奇怪，bin/gravity 的更新时间变了吗？
还有不需要放到`go/src`下面的。可以随便找个目录。不想动的话设下环境变量`GO111MODULE=on`

**Comment by 1454513232** [comment]
bin/gravity是重新生成的，但是修改的配置并没有生效，蛮奇怪的，最近发现很多gravity进程开启后，数据库的负载会上去，所以还是不能那么多同步进程

**Comment by Ryan-Git** [comment]
从库多了肯定会有压力啊。可以丢到一个mq再做分发

**Comment by 1454513232** [comment]
ok，谢谢
