### ISSUE TITLE
mysql->tidb filter 过滤不生效

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#252]
在mysql2tidb同步时，由于某个库下的表错误报错，进行过滤表操作发现并没有生效
在outpput 及input同级配置：
"filters": [
      {
        "type": "reject",
        "config": {
          "match-schema": "sqltakeouttest",
          "match-table": [
            "wm_template_messages*"
          ]
        }
      }
    ],
 
报错
![图片](https://user-images.githubusercontent.com/31116868/71673068-b312be00-2db2-11ea-857d-99302c2db98f.png)

请问我该怎么处理 过滤配置未生效的问题

**Comment by Ryan-Git** [comment]
还没到过滤器就挂了。为啥主键是空？

**Comment by zhanjianS** [comment]
ALTER TABLE `wm_template_messages`
ADD COLUMN `id`  int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增ID',
DROP PRIMARY KEY,
ADD PRIMARY KEY (`id`);

之前有这种操作，是这个导致的吗

**Comment by Ryan-Git** [comment]
是的，建议从最新的位置开始。没有主键会有很多问题。

**Comment by zhanjianS** [comment]
谢谢！ 我已经手动修改gtid位置跳过了，
我还是存在疑问 我这个是删除主键，然后新增一个主键，不是没有主键，这个解析出来的语句也很奇怪，说列不匹配 及REPLACE INTO 后面的value也对不上

![图片](https://user-images.githubusercontent.com/31116868/71712980-a342ba80-2e42-11ea-8e7f-6d80a72ab609.png)

**Comment by Ryan-Git** [comment]
第二个，tidb 的 alter 是拆开的，没法一个语句做三件事，再加上异步执行 DDL，是可能 DDL 返回后还没有加列完成的。一般重试就行了。

第一个有点奇怪。之前的主键是什么？这是第一次挂吗？

**Comment by zhanjianS** [comment]
是第一次遇见这种情况，之前的主键是 `template_id` varchar(50) ，挂了之后, 看了tidb的表结构跟mysql表结构一样，重新暂停任务重启也是同样的错误

**Comment by Ryan-Git** [comment]
可以看下 binlog，这条日志是在 ddl 之前还是之后？

**Comment by zhanjianS** [comment]
是在ddl之后的

**Comment by Ryan-Git** [comment]
> 是在ddl之后的

在 ddl 之后为啥没有 id 列？

**Comment by zhanjianS** [comment]
之后这个表 执行了一次 INSERT INTO wm_template_messages (`template_id`, `scene`, `name`, `content`, `type`, `status`, `created_at`, `updated_at`, `template_type`)
VALUES ('3450', 'ORDER_PAY_SUCCESS', '订单支付成功通知', '订单编号、订单金额、订单商品、下单时间', '1', '1', '1522304070', '1522304070', '2');
看着也是这个语句导致的报错

**Comment by xialuo1990** [comment]
@zhanjianS 能复现？

**Comment by zhanjianS** [comment]
@xialuo1990  
  复现不了, 同样的修改表结构操作来了一次，主键为空的情况没有再次发生
   可能由于 tidb不支持添加自增列 删除主键及修改主键的操作，当时人工操作介入比较多，导致一些不可控的因素。
@Ryan-Git  再次感谢
