### ISSUE TITLE
MySQL5.5无法建立_gravity库

### ISSUE THREAD

**Issue by qinglang15** [moiot/gravity#255]
源端可以不建立gravity库嘛？
我在配置文件里，注释掉internal-db-name = "_gravity"，为什么源端还会建立gravity库？

**Comment by qinglang15** [comment]
gravity建表语句是：
root@localhost : _gravity 02:40:22> CREATE TABLE IF NOT EXISTS _gravity.gravity_positions (
    ->                  name VARCHAR(255) NOT NULL,
    ->                  stage VARCHAR(20) NOT NULL DEFAULT 'unknown',
    ->                  position MEDIUMTEXT,
    ->          created_at DATETIME NOT NULL DEFAULT now(),
    ->          updated_at DATETIME NOT NULL DEFAULT now() ON UPDATE now(),
    ->                  PRIMARY KEY(name)
    ->          );
ERROR 1067 (42000): Invalid default value for 'created_at'

**Comment by Ryan-Git** [comment]
1、内部库用于存储位点，心跳消息等，是一定会建的。
2、5.5 还没有 gtid，gravity 以 gtid 为位点，即最低版本需要 5.7。

**Comment by qinglang15** [comment]
我源端是mysql5.5，我只做全量同步，不做增量同步，也不行。。。
5.6有的gtid，同步5.7正常

**Comment by Ryan-Git** [comment]
除了建表还报啥错？

**Comment by qinglang15** [comment]
建表报错后，直接退出了。
后来我手工修改了_gravity库里那2个表的列属性，改成timestamp，mysql5.5一个表只能有1个列是now()，并手工创建这2个表。
再启动程序，还是报相同的错误，程序又把我之前去掉的列属性加上了。然后退出。

**Comment by qinglang15** [comment]
咱们程序能不能加上这个功能：
1 如果没开启GTID，就只做全量同步（最简单），比如mysql5.1/5.5也能用了。目前程序建表语法不兼容老版本，手工建表也不行；
2 如果没开启GTID，通过binlog文件和位置单项同步（较复杂）；

**Comment by Ryan-Git** [comment]
> 建表报错后，直接退出了。
> 后来我手工修改了_gravity库里那2个表的列属性，改成timestamp，mysql5.5一个表只能有1个列是now()，并手工创建这2个表。
> 再启动程序，还是报相同的错误，程序又把我之前去掉的列属性加上了。然后退出。

这样没用，改一下[建表代码](https://github.com/moiot/gravity/blob/989fa5458b6749af95bf9560959a407af8534a06/pkg/position_repos/mysql_repo.go#L44)才行。

**Comment by qinglang15** [comment]
我修改了pkg/position_repos/mysql_repo.go文件，从新建库sql如下：
create database _gravity; 
use _gravity;
CREATE TABLE `gravity_positions` (
  `name` varchar(255) COLLATE utf8_bin NOT NULL,
  `stage` varchar(20) COLLATE utf8_bin NOT NULL DEFAULT 'unknown',
  `position` mediumtext COLLATE utf8_bin,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`name`)
);
CREATE TABLE `gravity_heartbeat_v2` (
  `name` varchar(255) NOT NULL,
  `offset` bigint(20) DEFAULT NULL,
  `update_time_at_gravity` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_time_at_source` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`name`)
);
再启动程序，正在做全量同步中。。。。。。但程序日志又报错了：
{"level":"fatal","msg":"Error 1067: Invalid default value for 'created_at'\n/data/wks_golang/src/github.com/moiot/gravity/pkg/position_repos/mysql_repo.go:112: \n/data/wks_golang/src/github.com/moiot/gravity/pkg/inputs/mysqlbatch/input.go:155: \n/data/wks_golang/src/github.com/moiot/gravity/pkg/app/server.go:122: ","time":"2020-01-17T14:04:44+08:00"}
我再查查，还要再改另一个表是吧？

**Comment by qinglang15** [comment]
现在全量同步完了，行数都对。
最后的报错内容，和之前的一样。全量同步完，就自动退出了。
如何破呀，大神。。。

**Comment by Ryan-Git** [comment]
全量同步完退出是正常行为，但是报错就不正常了。还是在`mysql_repo.go:112`这里报错？那就奇怪了，同步完不应该执行到这里了。

**Comment by qinglang15** [comment]
报错内容一样：Invalid default value for 'created_at'：报错文件还是之前的三个。
gravity/pkg/position_repos/mysql_repo.go:112: 
gravity/pkg/inputs/mysqlbatch/input.go:155: 
gravity/pkg/app/server.go:122
我又检查了这3个文件，
gravity/pkg/position_repos/mysql_repo.go:112: 第112的代码时：
    110         _, err = db.Exec(fmt.Sprintf("%s%s", repo.annotation, createPositionTableStatement))
    111         if err != nil {
    112                 return errors.Trace(err)
    113         }

gravity/pkg/inputs/mysqlbatch/input.go:155: 第155行代码：
    153 func (plugin *mysqlBatchInputPlugin) NewPositionCache() (position_cache.PositionCacheInterface, error) {
    154         if err := plugin.positionRepo.Init(); err != nil {
    155                 return nil, errors.Trace(err)
    156         }

gravity/pkg/app/server.go:122：第122行代码：
    121         if p, err := newer.NewPositionCache(); err != nil {
    122                 return nil, errors.Trace(err)
    123         } else {
    124                 server.PositionCache = p
    125         }
    126         return server, nil

我查了 "created_at" 关键字，就一个地方
[root@BJ86-26 pkg]# grep -r "created_at" *
position_repos/mysql_repo.go:        created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
我也不知道为什么了。。。

**Comment by Ryan-Git** [comment]
直接在`mysql`执行这个建表语句不报错吗？实在不行这两列删掉试试

**Comment by qinglang15** [comment]
MySQL5.5执行不报错，2个表都建立了

**Comment by Ryan-Git** [comment]
另外得是 `CREATE TABLE IF NOT EXISTS`，每次启动都会尝试建的。
