### ISSUE TITLE
mysql->tidb分库分表配置求助

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#257]
有两个问题请问下：
1、在同步时如果不考虑分库分表合并，直接配置match
`             "match-schema": "*",
            "match-table": "*",
            "target-schema": "*",
            "target-table": "*"  `
就可以，需要分库分表同步时，按照
         "match-schema": "test*",
            "match-table": "test_table*",
            "target-schema": "test",
            "target-table": "test_table"  
进行配置， 如果有同库的的不同表同步 比如test*.test2_table到test.test2_table ，或者不同库的的不同表同步 test3*.test3_table到test3.test3_table, 就需要另外在写一个match，这样就需要写很多个match  有没有别的写法?

2、在我指定表同步时，后新增表同步的话，现在新增表的历史数据是不会同步过来的，gravity有办法可以同步新增表的历史数据吗？
谢谢！

**Comment by Ryan-Git** [comment]
1、schema/table name 用不同的规则改写了，看起来没有别的办法。可以给 router 新加功能，但怎么抽象还要好好考虑一下。

2、令原来的 gravity 任务为 A，我们自己的做法是另外起一个 gravity B 同步新增表（包括历史）。B 追平后暂停 A，修改 A 的配置，确认 B 的位点超过 A 后关闭 B，再启动 A。

**Comment by zhanjianS** [comment]
明白了，十分感谢！
