### ISSUE TITLE
gravity双向写入，如何配置

### ISSUE THREAD

**Issue by qinglang15** [moiot/gravity#259]
我的配置如下：
[input.config]
ignore-bidirectional-data = false

[output.config.execution-engine]
use-bidirection = true

测试不成功。。。

**Comment by Ryan-Git** [comment]
ignore-bidirectional-data 表示输入端是否忽略双向流量，需要是 true。
use-bidirection 表示输出端是否标记自身流量，也要是 true。

**Comment by qinglang15** [comment]
请大神看看我的配置，两处bidirection都是true，但还是不行。现在单向的全量+增量都正常，应该是其他地方有问题吧？
name = "m2m_test9"
internal-db-name = "_gravity"

[input]
type = "mysql"
mode = "replication"  

[input.config]
ignore-bidirectional-data = true
nr-scanner = 10
table-scan-batch = 10000
batch-per-second-limit = 1
max-full-dump-count = 10000

[input.config.source]
host = "10.6.1.4"
username = "_gravity"
password = "A"
port = 3408
max-open = 20
max-idle = 20

[[input.config.table-configs]]
schema = "test"
table = "*"
[[input.config.table-configs]]  
schema = "test1"
table = "*"

#[input.config.start-position]
#binlog-gtid = "2778ac67-1a2b-11e9-bb6d-525400779e4d:1-3715183:4038990-5667080:6665844-7187563:7667454-7676284,a83c40e9-2610-11e9-9a0e-6c92bf336d18:1-3257,fabc4816-1a2d-11e9-aa0a-5254007783e2:1-14"

[output]
type = "mysql"

[output.config]
enable-ddl = true 

[output.config.target]
host = "10.6.1.1"
username = "_gravity"
password = "A"
port = 3409
max-open = 20
max-idle = 20

[[output.config.routes]]
match-schema = "test"
match-table = "*"
target-schema = "test_r"
target-table = "*"

[[output.config.routes]]
match-schema = "test1"
match-table = "*"
target-schema = "test1_r"
target-table = "*"

[output.config.execution-engine]
use-bidirection = true

**Comment by Ryan-Git** [comment]
不行具体是指？操作流程是什么样的，预期结果是什么，实际结果是什么

**Comment by qinglang15** [comment]
目标：A库是生产，B库是空库，计划A全量-->B后，程序双写，做双向同步。
流程：A全量-->B正常，程序开始双写，A增量-->B正常，但是B增量-->失败。
配置：是上面发的，只开了一个gravity。莫非是要启2个gravity嘛？

**Comment by Ryan-Git** [comment]
对啊。。。还要启动一个 B -> A 的 gravity

**Comment by qinglang15** [comment]
哈哈，原来如此，我以为1个程序能双向同步。那我再试试。
那2套程序的 四处bidirection都是true对吧。
还有端口怎么配置，我想一台机器，启动2个程序。

**Comment by Ryan-Git** [comment]
命令行参数，`-http-addr`, 默认`:8080`

**Comment by qinglang15** [comment]
多谢大神，我试试。等我好消息，哈

**Comment by qinglang15** [comment]
我的启动命令：nohup bin/gravity -http-addr 8081 -config example-mysql2mysql-full-20200106-14-revok.toml >> logs/`date +\%Y\%m\%d_\%H\%M\%S`_revoke.log 2>&1 &
日志报错：{"level":"fatal","msg":"http error: listen tcp: address 8081: missing port in address","time":"2020-01-20T17:38:51+08:00"}

**Comment by qinglang15** [comment]
弄出来了，谢谢大神!!!

**Comment by qinglang15** [comment]
谢谢
