### ISSUE TITLE
mysql->kafka有大批量更新操作时，任务会一直卡着重启？

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#261]
mysql->kafka有大批量更新操作时，任务会一直卡着重启？
主要错误日志如下：
![图片](https://user-images.githubusercontent.com/31116868/74311441-74592600-4daa-11ea-8ec4-e9926ce0d1ce.png)

抱歉， grafana没有加实例的详情数据流入流出监控

**Comment by zhanjianS** [comment]
非常感谢，修改了  scheduler.config.healthy-threshold 的参数为3600之后，单位为秒，就可以了

**Comment by Ryan-Git** [comment]
这种情况应该优化一下自动加一个心跳消息

**Comment by zhanjianS** [comment]
自动加一个心跳信息是指这个配置吗？

**Comment by Ryan-Git** [comment]
> 自动加一个心跳信息是指这个配置吗？

不是。希望能自动应对这个场景，issue 留着吧，等 pr 关。
