### ISSUE TITLE
Can support Mariadb GTID binlog format？

### ISSUE THREAD

**Issue by dingyiran** [moiot/gravity#262]
Can support Mariadb GTID binlog format？

If not，is there some plan to support it?

**Comment by Ryan-Git** [comment]
No. As I know there's just a few difference and our parsing lib [go-mysql](https://github.com/siddontang/go-mysql) has support for it. You're welcome for contribution :)

**Comment by dingyiran** [comment]
tidb从mysql 同步的工具 syncer 是支持mariadb binglog format的，它用的类库也是go-mysql 吗？若是，我这边可以参考下

**Comment by Ryan-Git** [comment]
> tidb从mysql 同步的工具 syncer 是支持mariadb binglog format的，它用的类库也是go-mysql 吗？若是，我这边可以参考下

是的，都基于 go-mysql。
