### ISSUE TITLE
mysql 到 kafka  数字1000变成 1,000

### ISSUE THREAD

**Issue by selectliu** [moiot/gravity#266]
mysql到kafka ，数字1000变成 1,000。能否不加个逗号

**Comment by Ryan-Git** [comment]
没太懂，列是什么类型？

**Comment by selectliu** [comment]
列是decimal(15,2)类型。   解析出来的是1,000 。比如下面图片里的amount字段，是decimal(15,2)类型
![图片](https://user-images.githubusercontent.com/7233990/77270722-b2216680-6ce7-11ea-9c42-0bb7431b0f73.png)

![图片](https://user-images.githubusercontent.com/7233990/77270705-a2a21d80-6ce7-11ea-96b1-40bff4f5cce3.png)

**Comment by Ryan-Git** [comment]
贴下版本号和配置，我试了下没有分隔符。
```sql
CREATE TABLE `ttt` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `v` int(11) NOT NULL,
  `d` decimal(15,2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
```
{"level":"info","msg":"111111111: {\"version\":\"0.1\",\"database\":\"test\",\"table\":\"ttt\",\"type\":\"update\",\"ts\":1584978767,\"time_zone\":\"Asia/Shanghai\",\"host\":\"127.0.0.1\",\"data\":{\"d\":\"1225.23\",\"id\":\"1\",\"v\":\"1\"},\"old\":{\"d\":\"1000\",\"id\":\"1\",\"v\":\"1\"},\"pks\":{\"id\":\"1\"}}","time":"2020-03-23T23:52:47+08:00"}
```

**Comment by selectliu** [comment]
v0.9.69-debug  这个版本，配置如下，ip地址隐掉了。
{
  "command": [
    "/gravity",
    "-config=/etc/gravity/config.json"
  ],
  "paused": false,
  "lastUpdate": "2020-02-04T03:30:57Z",
  "config": {
    "name": "kafka2mys",
    "version": "1.0",
    "input": {
      "type": "mysql",
      "mode": "stream",
      "config": {
        "source": {
          "host": "#",
          "max-idle": 3,
          "max-open ": 3,
          "password": "#",
          "port": #,
          "username": "#"
        },
        "start-position": {
          "binlog-gtid": "f1bd3a09-00fd-11ea-8ed8-ec0d9ad47960:1-126622"
        }
      }
    },
    "output": {
      "type": "async-kafka",
      "config": {
        "kafka-global-config": {
          "broker-addrs": [
            "#:9092",
            "#:9092"
          ],
          "mode": "async"
        },
        "routes": [
          {
            "dml-topic": "test",
            "match-schema": "sqldataviewtest",
            "match-table": [
              "test*",
              "zm*",
              "wm*",
              "vote*"
            ]
          },
          {
            "dml-topic": "sqlretatest",
            "match-schema": "sqlretatest",
            "match-table": [
              "zm_addresses",
              "zm_order_codes",
              "zm_order_group_infos",
              "zm_order_items",
              "zm_orders",
              "zm_order_subinfos",
              "zm_order_pick_ups"
            ]
          },
          {
            "dml-topic": "sqlqmaitest",
            "match-schema": "sqlqmaitest",
            "match-table": [
              "zm_addresses",
              "zm_user_wealths",
              "zm_users",
              "zm_accounts",
              "zm_stores",
              "zm_store_weapps",
              "zm_orders"
            ]
          },
          {
            "dml-topic": "sqlgoodstest",
            "match-schema": "sqlgoodstest",
            "match-table": [
              "gs_store_goods"
            ]
          },
          {
            "dml-topic": "test",
            "match-schema": "ptkilldb",
            "match-table": [
              "heartbeats*"
            ]
          },
          {
            "dml-topic": "orders",
            "match-schema": "ordertest*",
            "match-table": [
              "*"
            ]
          },
          {
            "dml-topic": "sqlptfwtest",
            "match-schema": "sqlptfwtest*",
            "match-table": [
              "zm_orders",
              "zm_goods"
            ]
          }
        ]
      }
    }
  },
  "configHash": "6dd7f8bf9d",
  "image": "registry-vpc.cn-shanghai.aliyuncs.com/qmbase/gravity:v0.9.69-debug"
}

**Comment by selectliu** [comment]
还有人关注吗

**Comment by Ryan-Git** [comment]
我在 0.9.69 上没有复现这个问题。
```json
{"version":"0.1","database":"test","table":"ttt","type":"update","ts":1585203269,"time_zone":"Asia/Shanghai","host":"127.0.0.1","data":{"d":"11015.23","id":"1","v":"1"},"old":{"d":"100015.23","id":"1","v":"1"},"pks":{"id":"1"}}
```

![image](https://user-images.githubusercontent.com/5906907/77616352-629f9c80-6f6c-11ea-97c6-7393d1a6aff1.png)

表结构同上，mysql 版本 5.7.28
