### ISSUE TITLE
mysql-insert-ignore 执行引擎无法处理update

### ISSUE THREAD

**Issue by liuxinwang** [moiot/gravity#268]
最近在测试mysql-replace-engine执行引擎，从分库表汇总到单库表，偶发有死锁的情况，所以想用mysql-insert-ignore执行引擎，避免replace into导致的死锁；在测试时对于update的操作，gravity直接处理成了insert ignore into，这样会导致update操作不会进行，建议对于update操作可以解析为update语句进行同步执行，解析update语句的where条件可以使用全字段，这样可以利用到主键进行update。

**Comment by Ryan-Git** [comment]
是 rc 级别吗？
insert ignore 是全量导 tidb 时候用的，也用在全量增量一块儿跑的情况，改成 update 会影响这两个用例。

**Comment by liuxinwang** [comment]
是rc级别下。

**Comment by Ryan-Git** [comment]
能看下死锁信息？rc照理不应该死锁的。

另外麻烦贴一下版本号和配置文件。

**Comment by Ryan-Git** [comment]
可以用`mysql-insert-on-duplicate-key-update`这个
