### ISSUE TITLE
mysql->kafka 生成的data中的json字段的顺序和mysql数据表的字段顺序是非一致的

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#272]
mysql->kafka 生成的data中的json字段的顺序和mysql数据表的原有字段顺序是非一致的，我看json的字段应该是按字典顺序进行了排序

**Comment by Ryan-Git** [comment]
json 规范本身字段就不要求有序。序列化时候确实没看过按什么顺序。需要按原字段顺序是为啥？

**Comment by Ryan-Git** [comment]
有问题再开吧
