### ISSUE TITLE
mysql2tidb合库合表会一直卡在 然后容器不断重启

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#274]
请问下  mysql2tidb合库合表通道，当mysql端有一个update会更新一百万数据时，一直卡在这，然后容器不断重启

路由表写的比较多 有十几个，下面是scheduler的参数配置

  "scheduler": {
      "type": "batch-table-scheduler",
      "config": {
        "batch-size": 40,
        "healthy-threshold": 3600,
        "nr-worker": 400,
        "queue-size": 1024,
        "sliding-window-size": 1024
      }
    }

![图片](https://user-images.githubusercontent.com/31116868/79415267-7e341b00-7fdf-11ea-9f86-1924879d024c.png)

**Comment by Ryan-Git** [comment]
重启前后的日志呢？
再贴下 grafana 吧。

**Comment by zhanjianS** [comment]
这个就是重启之后的日志了  之前的话就一直是上面的日志
![图片](https://user-images.githubusercontent.com/31116868/79420991-88a8e180-7fec-11ea-917f-6cd41e372634.png)


这个图为存活的状态，其他的指标暂时没有
![图片](https://user-images.githubusercontent.com/31116868/79420834-497a9080-7fec-11ea-8db9-42f813df28a1.png)

**Comment by Ryan-Git** [comment]
Detail 那个 dashboard 没有？
还有 pod 的状态，是不是健康检查没过被删了

**Comment by zhanjianS** [comment]
detail 那个没有采集
pod的状态是健康检查没过就没删了

**Comment by Ryan-Git** [comment]
可以先手动改一下 Deployment 里健康检查的阈值，具体原因我再看看

**Comment by zhanjianS** [comment]
嗯呢，目前采取的方法是跳过那段gtid位置了，中间的直接丢弃了

**Comment by zhanjianS** [comment]
您好，请问下 ，我这边部署了最新的版本，还存在个问题，日志跟上面基本差不多

部署了五个通道，2个到kafka，3个到tidb，其中有一个到tidb，之前是好，在最近两小时任务会频繁重启，看pod内存占用会一直升高，内存由500m调到1g还是一样升高
![图片](https://user-images.githubusercontent.com/31116868/80360838-87ac6580-88b2-11ea-9c01-b7e38ee4a688.png)

![图片](https://user-images.githubusercontent.com/31116868/80361696-f6d68980-88b3-11ea-89a8-03d16c09bb1f.png)
