### ISSUE TITLE
监控指标与性能调优

### ISSUE THREAD

**Issue by dbaCT** [moiot/gravity#281]
Hi，各位大佬好！
我们最近在调研 DTS 工具，用于将来的异地多活架构中。初步测下来，gravity 是个很不错的方案。目前遇到几个问题，还请帮忙解答一下：
1. grafana 监控页面上的指标还是比较多的，有没有相关的说明文档，我似乎没找到；
2. 我们在测试过程中发现，同步经常会有较大的延迟，如何定位性能瓶颈，以及之后的性能调优的策略是什么样的；
3. gravity 有没有交流群。

**Comment by Ryan-Git** [comment]
1、确实还没有，我在 pannel 上加下描述吧。
2、具体要看监控了。作为参考我们的同步延迟80线在50ms以下，99线在500ms以下。主要还是取决于写入侧的性能。
3、二维码
![image](https://user-images.githubusercontent.com/5906907/81682990-0cd57400-9488-11ea-9f04-5777e05d74d4.png)

**Comment by dbaCT** [comment]
个人认为，对监控指标的全面了解，才能更好地进行性能调优。所以，我们迫切需要这方面的资料，万分期待！
我这边有如下 2 张监控图和部分参数，您看能不能暂时给个优化建议：

![企业微信截图_20200512211614](https://user-images.githubusercontent.com/46683377/81696179-30072000-9496-11ea-8c3b-5857b3d5e827.png)
![企业微信截图_20200512211648](https://user-images.githubusercontent.com/46683377/81696519-9429e400-9496-11ea-9fe4-046d23b3add8.png)

```
[output.config.target]
max-open = 32
max-idle = 32

[scheduler.config]
nr-worker = 64
batch-size = 1000
queue-size = 16384
sliding-window-size = 8192
```

非常感谢！

**Comment by Ryan-Git** [comment]
已经有 pr 了，但想调优还是得需要对实现比较了解才行。

是什么样的同步？这个看起来是读得不够快。

**Comment by dbaCT** [comment]
我们的测试环境很简单，同一个网段，目前是两个单实例 MySQL 做的单向同步，DB1 -> gravity -> DB2。
服务器配置 32核 CPU，64G 内存，1.4T SSD；MySQL 版本 5.7.29；操作系统 CentOS 7.6。
如果是读得不够快，需要调整哪些参数呢？
谢谢！

**Comment by Ryan-Git** [comment]
这是全量还是增量？增量的话这个配置 10w 行/秒的更新源端是怎么做到的。。

**Comment by dbaCT** [comment]
这是增量，我们在源端加了一点写压力。

**Comment by Ryan-Git** [comment]
不是一点了吧-。- 官方的压测都没这么多。
增量的话目前没办法了，看下 cpu 估计有一核（解析binlog）打满了。
还是比较奇怪的，这个压力 mysql 自己的主从同步估计都来不及。我们的经验 gravity 会比主从快很多。

**Comment by dbaCT** [comment]
好的，可能是我们太暴力了 😂
再请教另外一个问题，监控页面上有同步延迟相关的指标吗？我看了很多遍，似乎没找到符合延迟、或者靠得上边的指标。
谢谢！

**Comment by Ryan-Git** [comment]
第一行就是延迟。watermark 是流式计算里的概念。
event time 指从一行写入 binlog 到”写完“目标库的延迟。
process time 指从一行被 gravity 收到到”写完“目标库的延迟。
这里的”写完“指这一行及其前序所有行都写成功了。

**Comment by dbaCT** [comment]
event time 这个不太准吧？因为我时常能看到十几小时、甚至几天的延迟，但实际是不可能有那么大的。并且，我们在源端加压测试时，event time 值始终是 2.22x hour，这也并不是两端数据同步延迟的真正时长。

**Comment by Ryan-Git** [comment]
应该是准的，你的延迟是怎么看的？
值不变的话确实有问题，可以停写看看他降不降。

**Comment by dbaCT** [comment]
![企业微信截图_20200514201358](https://user-images.githubusercontent.com/46683377/81933165-83f14080-961f-11ea-9763-28dd9fa5cc26.png)

您也可以参考我之前贴出来那个监控图，时间线始终是平稳的。写操作停止，一段时间后，直接就是断崖式的下跌。

我的延迟是这么看的：源端每秒往一张表中写入当前的时间戳，目标端每秒读取那张表的最新记录，与当前的时间戳进行比较，得出差值。

**Comment by Ryan-Git** [comment]
想起来了，这种情况确实不太准。

目前的延迟直方图在延迟大的时候桶就比较宽了，其中有一个桶的范围是 0.5 小时到 2.33 小时，他的 95 线正好是 2.2 左右，按 Prometheus 的计算方式这个图是正常的，他的意思其实是延迟现在在 0.5 到 2.33 小时之间。

要很精确的话桶只能很窄，就需要很多桶，开销比较大。

如下，0~8秒2倍宽分了15个桶，16秒到150小时8倍宽分了6个桶。也就是8秒以内的延迟是相对精确的，再往上误差会比较大。一般我们超过1秒就告警了，再大的时候很精确意义不大，只是示意一下。
```go
var End2EndEventTimeHistogram = prometheus.NewHistogramVec(prometheus.HistogramOpts{
	Namespace: "gravity",
	Name:      "event_time_latency",
	Help:      "Latency of end to end event time in seconds.",
	Buckets:   append(prometheus.ExponentialBuckets(0.0005, 2, 15), prometheus.ExponentialBuckets(0.0005*(1<<15), 8, 6)...), // 0 ~ 8s, 16s ~ 150h
}, []string{PipelineTag})
```

**Comment by dbaCT** [comment]
明白了，非常感谢您的耐心解答！
