### ISSUE TITLE
请问跟logstash有什么区别呢？

### ISSUE THREAD

**Issue by yiippee** [moiot/gravity#282]
感谢你们团队的开源项目，
弱弱地请问一句：跟logstash有什么区别呢？
谢谢~

**Comment by Ryan-Git** [comment]
logstash-input-jdbc 是通过增量扫表实现的，限制要多一些。在输出上也无法直接同步到 mysql。
另外他不理解主键/唯一键，那在输出时的并发方面肯定粒度比较粗，估计就是表级别并发。

**Comment by yiippee** [comment]
我目前使用logstash面对大数据同步非常慢且占用内存大的问题，估计是分页造成的，logstash是采用子查询的方式来分页，这个网上也有讨论。
再请问，gravity可以自定义input的sql语句吗？我找了下，好像没找到配置，还是我哪里没理解对呢？谢谢。

**Comment by Ryan-Git** [comment]
我们增量是伪装从库拉的 binlog，不需要定义 sql 语句。有过滤需求的可以通过配置路由和过滤器实现。
全量可以自定义 where 条件，通过主键/唯一键分页。

**Comment by yiippee** [comment]
自定义sql语句的需求是，有时候需要连表查出结果，再同步到output的

**Comment by Ryan-Git** [comment]
那只能通过[自定义过滤器](https://github.com/moiot/gravity/blob/master/docs/2.0/05-filters-en.md#grpc-sidecar)实现了。抓 binlog 就没法直接 join。

**Comment by yiippee** [comment]
> 那只能通过[自定义过滤器](https://github.com/moiot/gravity/blob/master/docs/2.0/05-filters-en.md#grpc-sidecar)实现了。抓 binlog 就没法直接 join。

你好，抓binlog同步同时达到join的效果有个这样的方式，比如tab1 left join tab2 on tab1.id = tab2.tab1_id, 本来是join来获取结果数据再导入es中，但是binlog没法直接join，那tab1单个表通过id直接更新es中tab1负责那部分数据，同理tab2根据tab1_id也直接去更新es中tab2负责的那部分数据，因为是同一个id，所以更新的是同一条doc，这样可能会有并发问题，但实际场景很小。请问这样的方式是否可行啊？会有什么问题呢？谢谢谢谢。你们开源的这个项目对于学习数据库相关的知识很有帮助，再次感谢。

**Comment by Ryan-Git** [comment]
可以试一下社区贡献的[es model 输出](https://github.com/moiot/gravity/blob/master/docs/2.0/04-outputs.md#esmodel)。
并发更新到问题不大，es 有乐观并发控制
