### ISSUE TITLE
mysql-tidb gh-ost变更表结构后数据的列会错乱

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#284]
请问下 mysql-tidb gh-ost变更表结构后数据的列会错乱？

原先表结构：
CREATE TABLE `order_discounts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '用户id',
  `order_no` varchar(32) DEFAULT '' COMMENT '订单号',
  `item_id` varchar(32) DEFAULT NULL COMMENT '商品id',
  `discount_level` int(11) NOT NULL DEFAULT '0' COMMENT '优惠级别',
  `discount_id` varchar(64) DEFAULT NULL COMMENT '优惠id',
  `discount_type` int(11) NOT NULL DEFAULT '0' COMMENT '优惠类型',
  `discount_name` varchar(256) NOT NULL DEFAULT '' COMMENT '优惠名称',
  `discount_summary` varchar(1024) DEFAULT NULL COMMENT '优惠描述',
  `discount_amount` int(11) NOT NULL DEFAULT '0' COMMENT '优惠金额',
  `features` text DEFAULT NULL COMMENT '扩展信息',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '修改时间',
  `is_deleted` int(11) NOT NULL DEFAULT '0' COMMENT '删除标识',
  PRIMARY KEY (`id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_user_id_order_no` (`user_id`,`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

变更语句
ALTER TABLE order_discounts  ADD COLUMN `biz_type` INT ( 11 )
  NOT NULL DEFAULT '0' COMMENT '业务类型' AFTER id;

采用gh-ost变更，未开启ddl同步，tidb端的ddl是手动执行，
![图片](https://user-images.githubusercontent.com/31116868/83770114-437f6280-a6b3-11ea-8fd4-0ecc44e158c4.png)

修改tidb端的字段可以为null后
拿到的数据都是错行的

![图片](https://user-images.githubusercontent.com/31116868/83770184-57c35f80-a6b3-11ea-99b8-7fbb964315ef.png)

**Comment by zhanjianS** [comment]
补充一下
1 只有源端变更表结构这段时间的数据是错乱的。表结构变更完成后是正确的，
2 看情况默认值加到了最后一列，实际指定了字段位置在id的后面，导致的数据顺序错乱

**Comment by Ryan-Git** [comment]
目前不支持`AFTER id `这样用

**Comment by zhanjianS** [comment]
不支持AFTER id 是指tidb端嘛，如果mysql端有这种变更语句的话，tidb端是需要把字段加到最后面嘛？

**Comment by Ryan-Git** [comment]
跟目标端是啥关系不大，源端是 mysql 的话还不支持。
