### ISSUE TITLE
将编译好的文件放到其他服务器，启动报错，提示缺少插件

### ISSUE THREAD

**Issue by wwwwwwchun** [moiot/gravity#285]
将编译好的gravity放到其他服务器上，然后启动./gravity后，提示报错，报错内容如下：
{"level":"fatal","msg":"/data/go/src/github.com/moiot/gravity/pkg/outputs/mysql/mysql.go:86: failed to find plugin: /data/go/src/github.com
/moiot/gravity/pkg/registry/registry.go:83: empty plugin, type: sqlExecutionEngine, name: \n/data/go/src/github.com/moiot/gravity/pkg/app/s
erver.go:57: ","time":"2020-06-07T16:52:21+08:00"}

**Comment by Ryan-Git** [comment]
`sql-engine-config`配置不对

**Comment by wwwwwwchun** [comment]
加上这个选项后，问题解决了，谢谢了
[output.config.sql-engine-config]
type = "mysql-replace-engine"
