### ISSUE TITLE
如何配置多个MySQL下的数据库同步到一个MySQL中

### ISSUE THREAD

**Issue by AstonPudding** [moiot/gravity#287]
想要把MySQL A下面的a库，以及MySQL B下面的b库，传输到MySQL C中，这种情况下是不是要启动两个gravity进程，一个进程负责同步A到C，另一个负责同步B到C。能在一个配置文件中指定多个数据源吗。

**Comment by Ryan-Git** [comment]
不能，一个进程只能配置一个实例（一个实例的不同库可以）。

**Comment by AstonPudding** [comment]
像是上面这种情况，如果想要双向同步，是不是要起四个进程。两个负责A到C的双向同步，另外两个负责B到C的双向同步。

**Comment by Ryan-Git** [comment]
是的。进程比较多的话可以考虑[集群模式](https://github.com/moiot/gravity-operator)，管起来方便一点。

**Comment by AstonPudding** [comment]
谢谢！~
