### ISSUE TITLE
MySQL全量同步后，源端和目标端数据不一致，目标端少数据

### ISSUE THREAD

**Issue by wwwwwwchun** [moiot/gravity#288]
MySQL配置全量+增量模式后，在全量同步阶段，发现全量同步结束后，源端和目标端数据量不一致，目标端数据量比源端少很多，通过日志有如下显示：
{"level":"info","msg":"[mysqlBatchInputPlugin] closed","time":"2020-06-09T11:24:53+08:00"}
{"level":"info","msg":"[defaultPositionCache] closing","time":"2020-06-09T11:24:53+08:00"}
{"level":"info","msg":"[defaultPositionCache] closed","time":"2020-06-09T11:24:53+08:00"}
{"level":"info","msg":"DSN is _gravity:654321@tcp(10.2.5.10:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2020-06-09T11:24:53+08:00"}
{"level":"info","msg":"DSN is _gravity:654321@tcp(10.2.5.10:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2020-06-09T11:24:53+08:00"}
{"level":"info","msg":"DSN is _gravity:654321@tcp(10.2.5.10:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2020-06-09T11:24:53+08:00"}
{"level":"info","msg":"DSN is _gravity:654321@tcp(10.2.5.10:3306)/?interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\u0026parseTime=true\u0026collation=utf8mb4_general_ci\u0026loc=Local","time":"2020-06-09T11:24:53+08:00"}
{"level":"info","msg":"[binlog_checker] start","time":"2020-06-09T11:24:53+08:00"}
{"level":"info","msg":"[binlogTailer] start","time":"2020-06-09T11:24:53+08:00"}
{"level":"info","msg":"[binlogTailer] getBinlogStreamer gtid: c6431388-aea7-11e9-a2c2-6c92bf736439:1-2978948","time":"2020-06-09T11:24:53+08:00"}
{"level":"info","msg":"[TwoStageInputPlugin] incremental stage started","time":"2020-06-09T11:24:53+08:00"}
{"level":"info","msg":"[binlogTailer] skip rotate event: source binlog Name mysql-bin.000001, source binlog Pos: 4; store Name: mysql-bin.000001, store Pos: 854958265","time":"2020-06-09T11:24:53+08:00"}

**Comment by Ryan-Git** [comment]
贴一下表结构和配置。
比较常见的问题是表没主键，这种目前不支持。
另外如果源端在不断写入，全量结束后不一致是正常的，还要等增量追平才行。
最好是搭一下监控看看。不然得手动看同步到哪里了。可以 curl localhost:8080/status 看下当前位点，跟`mysql`里`show master status` 的当前`gtid`比较一下，差的比较多就是增量还没追上。

**Comment by wwwwwwchun** [comment]
刚才查了一下，这张表有主键，而且源端一直没有在写入。

**Comment by wwwwwwchun** [comment]
这个是表结构，
+------------+-------------+------+-----+---------+----------------+
| Field      | Type        | Null | Key | Default | Extra          |
+------------+-------------+------+-----+---------+----------------+
| id         | int(11)     | NO   | PRI | NULL    | auto_increment |
| code       | varchar(6)  | NO   |     | NULL    |                |
| o_state | varchar(30) | NO   |     | NULL    |                |
+------------+-------------+------+-----+---------+----------------+
配置文件如下：

name = "caiwu_to_arch"

internal-db-name = "_gravity"


[input]
type = "mysql"
mode = "replication"
[input.config]

ignore-bidirectional-data = true
[input.config.source]
host = "10.2.5.10"
username = "_gravity"
password = "123456"
port = 3306
[input.config.source-slave]
host = "10.12.5.11"
username = "_gravity"
password = "654321"
port = 3306

[output]
type = "mysql"

[output.config]
enable-ddl = true # 当前支持 create & alter table 语句。库表名会根据路由信息调整。

[output.config.target]
host = "10.2.5.10"
username = "_gravity"
password = "654321"
port = 3307
max-open = 20 # 可选，最大连接数
max-idle = 20 # 可选，最大空闲连接数，建议与 max-open 相同
[output.config.sql-engine-config]
type = "mysql-replace-engine"
[output.config.sql-engine-config.config]

tag-internal-txn = true
[[output.config.routes]]
match-schema = "order"
match-table = "*"
target-schema = "order"
target-table = "*"
[[output.config.routes]]
match-schema = "c_order"
match-table = "*"
target-schema = "c_order"
target-table = "*"

**Comment by Ryan-Git** [comment]
`10.12.5.11` 这个从库和主库是一致的？

**Comment by wwwwwwchun** [comment]
是一致的，刚才检查了一遍了，count(*)的数量是一样的

**Comment by wwwwwwchun** [comment]
这个会不会和目标端的数据库参数设置有关系，目标端lock_wait_time的参数设置的是5s

**Comment by Ryan-Git** [comment]
> 这个会不会和目标端的数据库参数设置有关系，目标端lock_wait_time的参数设置的是5s

这个应没啥影响。

有点奇怪，全量阶段的日志贴一下？这两天我们还同步了好几个库来着。。没什么问题啊

**Comment by Ryan-Git** [comment]
@wwwwwwchun 有更新吗

**Comment by wwwwwwchun** [comment]
我准备重新搭建一套环境，再重新测试一下。

**Comment by Ryan-Git** [comment]
好的。
看到开了双向同步要提醒一下，双向过程中同一行不能在两个实例同时更新，不然同步的结果不确定，可能会丢失更新（上帝视角的老版本覆盖新版本）。一般用的方式是根据主键/唯一键逐步切流量到新实例。另外就是双向同步不能用默认的自增主键，两边会相互覆盖。可以通过设置自增步长，使用发号器等方式解决。

**Comment by Ryan-Git** [comment]
还有问题吗？

**Comment by wwwwwwchun** [comment]
日志里面一直有这个提示，interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\，
是不是目标端的innodb_lock_wait_timeout和lock_wait_timeout两个参数需要设置为0才行呀？

**Comment by wwwwwwchun** [comment]
在目标端把innodb_lock_wait_timeout这个参数设置为28800后，重新全量抽取数据就好了，但是这样的前提只能是保证数据量在8小时内抽完才行，对于大数据量的情况，超过8小时后怎么办？还有一个是一般生产环境这个参数不会让设置为28800这么大的值，能不能在gra的配置文件里加一个这个参数，session级别的设置为8小时，这样不会对全局产生影响。

**Comment by Ryan-Git** [comment]
> 日志里面一直有这个提示，interpolateParams=true\u0026timeout=5s\u0026readTimeout=5s\u0026writeTimeout=5s\，
> 是不是目标端的innodb_lock_wait_timeout和lock_wait_timeout两个参数需要设置为0才行呀？

没碰到过这种情况。这个提示只是设读写超时

**Comment by Ryan-Git** [comment]
有问题再开
