### ISSUE TITLE
Mysql 8.18 同步至 Tidb 4.0 出现大量警告

### ISSUE THREAD

**Issue by smilenazy** [moiot/gravity#291]
{"level":"warning","msg":"[sliding_window] item not ack after 47.349907 seconds. 
{"level":"warning","msg":"[sliding_window] item not ack after 48.934431 seconds. 
{"level":"warning","msg":"[sliding_window] item not ack after 55.742583 seconds. 
{"level":"warning","msg":"[sliding_window] item not ack after 48.349904 seconds. 
{"level":"warning","msg":"[sliding_window] item not ack after 49.934421 seconds. 
{"level":"warning","msg":"[sliding_window] item not ack after 49.350198 seconds. 
{"level":"warning","msg":"[sliding_window] item not ack after 50.934416 seconds. 
{"level":"warning","msg":"[sliding_window] item not ack after 50.349864 seconds. 
{"level":"warning","msg":"[sliding_window] item not ack after 51.934438 seconds.
数据依旧在同步 但是同步速度极度缓慢
数据源依旧会更新update_at 时间 position 内容不变

我看了以往的Issues 尝试通过加大提高并发量去解决 
[output.config.target]
max-open = 200
max-idle = 200

[scheduler]
type = "batch-table-scheduler"
[scheduler.config]
nr-worker = 200
修改了参数以后 程序拉起来以后停止同步数据 程序类似假死状态

{"level":"info","msg":"[Server] started","time":"2020-06-30T21:13:23+08:00"}
{"level":"info","msg":"[gravity] stop with signal hangup","time":"2020-06-30T21:19:12+08:00"}
{"level":"info","msg":"[Server] closing..","time":"2020-06-30T21:19:12+08:00"}
{"level":"info","msg":"[scanner server] closing...","time":"2020-06-30T21:19:12+08:00"}

若干分钟后 进程结束。。。 然后远端position 表数据无变化

观察了1小时 几个表一起共计同步了不到400W数据。。。

**Comment by Ryan-Git** [comment]
这种一般是写得慢，看下`gravity`和`TiDB`的监控

**Comment by smilenazy** [comment]
> 这种一般是写得慢，看下`gravity`和`TiDB`的监控

我感觉是TIDB 的问题。。。 真的慢  但是这个告警应该没事儿吧

**Comment by Ryan-Git** [comment]
集群模式延迟太大会自杀。单机没啥影响。不过追不上总归不是个事儿啊。。

**Comment by smilenazy** [comment]
> 集群模式延迟太大会自杀。单机没啥影响。不过追不上总归不是个事儿啊。。

5E数据 同步了10多天。。。 但是我发现TIDB是慢。。。 就是用数据泵灌入数据 也是慢。。。 但是我感觉这个应该没这么高延迟啊。。。 等追平再观察下  

现在看还算OK 只要延迟不拉开也还能接受

**Comment by zhanjianS** [comment]
我也遇到了相同的问题，积压的比较严重
![图片](https://user-images.githubusercontent.com/31116868/96122272-d1057580-0f23-11eb-8cd8-673f15764b06.png)
![图片](https://user-images.githubusercontent.com/31116868/96122341-ebd7ea00-0f23-11eb-827a-b81dbc48be8c.png)
![图片](https://user-images.githubusercontent.com/31116868/96122392-001be700-0f24-11eb-8695-0d28e6de5580.png)

队列数据很多，输入跟输出都很少，这个该怎么排查

**Comment by Ryan-Git** [comment]
> 我也遇到了相同的问题，积压的比较严重

截图完整一点。输出 238 也太慢了。每个阶段的延迟都有呀

**Comment by zhanjianS** [comment]
> > 我也遇到了相同的问题，积压的比较严重
> 
> 截图完整一点。输出 238 也太慢了。每个阶段的延迟都有呀



这是监控里面的图 ，输出跟队列的图没数据有点问题， 处理的时间好长，一直不下来，这个跟什么有关系
![图片](https://user-images.githubusercontent.com/31116868/96149349-ca82f800-0f3b-11eb-8b46-0aba3e111cd6.png)
![图片](https://user-images.githubusercontent.com/31116868/96149532-028a3b00-0f3c-11eb-9261-0993a503138d.png)

![图片](https://user-images.githubusercontent.com/31116868/96151355-e7b8c600-0f3d-11eb-9d90-2a144ca86884.png)

**Comment by Ryan-Git** [comment]
为啥没数据。。队列的监控比较关键
看起来读的很慢，写的并不慢，如果队列是空，那就是读取源端有问题。源端是啥，怎么读的？

**Comment by zhanjianS** [comment]
> 
> 
> 为啥没数据。。队列的监控比较关键
> 看起来读的很慢，写的并不慢，如果队列是空，那就是读取源端有问题。源端是啥，怎么读的？

源端是mysql ，队列的监控估计是grafana的查询语句有问题  下面这张图是总览图标的数据
![图片](https://user-images.githubusercontent.com/31116868/96213126-d1951f00-0faa-11eb-8ae2-a65407084105.png)

今天早上看了监控, 昨天晚上凌晨3,4点的时候处理速度上来了，现在已经恢复了，怀疑跟这边的k8s有些关系
