### ISSUE TITLE
怎么使用gravity将大表根据分区键分到各个表？

### ISSUE THREAD

**Issue by jmbkeyes** [moiot/gravity#292]
怎么使用gravity将大表根据分区键分到各个表？
怎么指定分片键？

**Comment by Ryan-Git** [comment]
分表是用 proxy 还是 sdk 模式？proxy 的话直接写就可以了，不用理解分区键。 sdk 的话目前没有很好的办法直接支持，可以用 sdk 自己写个简单的 proxy。。。

**Comment by jmbkeyes** [comment]
好的，明白了，需要自己处理的， 谢谢！
