### ISSUE TITLE
全量同步失败

### ISSUE THREAD

**Issue by byronjxb** [moiot/gravity#293]
源数据库：127.0.0.1:3309
目标数据库：127.0.0.1:3311
同步数据库：test

配置如下：
cat config/test_dev.toml 

name = "mysql2mysql"
internal-db-name = "_gravity"

[input]
type = "mysql"
mode = "batch"

[input.config]
ignore-bidirectional-data = true

[input.config.source]
host = "127.0.0.1"
username = "_gravity"
password = "xxxx"
port = 3309

[output]
type = "mysql"

[output.config]
enable-ddl = true

[output.config.target]
host = "127.0.0.1"
username = "_gravity"
password = "xxxxxxxx"
port = 3311

[output.config.execution-engine]
use-bidirection = true

[[output.config.routes]]
match-schema = "test"
match-table = ""
target-schema = "test"
target-table = ""

[output.config.sql-engine-config]
type = "mysql-replace-engine"

[output.config.sql-engine-config.config]
tag-internal-txn = true
启动进程：./bin/gravity -config ./config/test_dev.toml -L debug -log-file xxxx_db.log
报以下信息：
{"level":"info","msg":"[batchScheduler] table buffer closed","time":"2020-09-15T06:28:23Z"}
{"level":"info","msg":"[batchScheduler] worker closed","time":"2020-09-15T06:28:23Z"}
{"level":"info","msg":"[batchScheduler] table latch closed","time":"2020-09-15T06:28:23Z"}
{"level":"info","msg":"[batchScheduler] sliding window closed","time":"2020-09-15T06:28:23Z"}
{"level":"info","msg":"[Server] scheduler closed","time":"2020-09-15T06:28:23Z"}
{"level":"info","msg":"[Server] output closed","time":"2020-09-15T06:28:23Z"}
{"level":"info","msg":"[defaultPositionCache] closing","time":"2020-09-15T06:28:23Z"}
{"level":"info","msg":"[defaultPositionCache] closed","time":"2020-09-15T06:28:23Z"}
{"level":"info","msg":"[Server] position store closed","time":"2020-09-15T06:28:23Z"}
{"level":"info","msg":"[Server] stopped","time":"2020-09-15T06:28:23Z"}

**Comment by Ryan-Git** [comment]
不是跑完了吗？没看到报错呀。全量跑完进程会退出。

**Comment by byronjxb** [comment]
只同步了差不多四分之一的数据表。
日志提示以下的这些表都是未同步的，但也没报啥错误。。。
{"level":"info","msg":"added for batch: aa.ks_students","time":"2020-09-15T07:02:40Z"}
{"level":"info","msg":"added for batch: aa.ks_subjects","time":"2020-09-15T07:02:40Z"}
{"level":"info","msg":"added for batch: aa.ks_teachers","time":"2020-09-15T07:02:40Z"}
{"level":"info","msg":"added for batch: aa.ks_teachers_subjects","time":"2020-09-15T07:02:40Z"}
{"level":"info","msg":"added for batch: aa.ku_privileges","time":"2020-09-15T07:02:40Z"}
{"level":"info","msg":"added for batch: aa.ku_users","time":"2020-09-15T07:02:40Z"}
{"level":"info","msg":"added for batch: aa_porms","time":"2020-09-15T07:02:40Z"}
{"level":"info","msg":"[Server] started","time":"2020-09-15T07:02:40Z"}

**Comment by byronjxb** [comment]
是不是主键的原因？？

**Comment by Ryan-Git** [comment]
不支持没主键的。
这些表没数据？

**Comment by byronjxb** [comment]
未同步的表是有数据的，相反，已经同步过去的是空数据。。。

**Comment by Ryan-Git** [comment]
这个日志跟配置对不上？配置里路由的只有 test 库，这个日志都是 aa 库

**Comment by byronjxb** [comment]
我是把数据库和关键信息隐藏了，抱歉，给你造成了困扰~

**Comment by Ryan-Git** [comment]
贴下完整的日志吧

**Comment by Ryan-Git** [comment]
好了？

**Comment by byronjxb** [comment]
没有，考虑后面的需要 从aws同步数据，但aws有些参数无法开启，使用gravity会失败，所以还是写个脚本同步吧
