### ISSUE TITLE
通过gravity ，从mysql 传入tidb4.0，写入速度很慢

### ISSUE THREAD

**Issue by tiger-k8s** [moiot/gravity#294]
tidb慢日志里 ，有大量的replace into的sql，这个应该的tidb的问题，有什么优化的方法吗？
同时在tidb.log里，有大量的写冲突的信息：
[conn=13986] [label=general] [error="[kv:9007]Write conflict, txnStartTS=420019931438645308, conflictStartTS=420019931438645301, conflictCommitTS=420019931438645310, key={tableID=85, handle=1} primary={tableID=85, handle=1} [try again later]"] [txn="Txn{state=invalid}"]

表已经配置了SHARD_ROW_ID_BITS 4 和 PRE_SPLIT_REGIONS 2 ，避免了写热点问题。
表结构如下：

mysql> show create table  order_records \G
*************************** 1. row ***************************
       Table: order_records
Create Table: CREATE TABLE `order_records` (
  `id` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '' ,
  `api_bill_no` varchar(255) COLLATE utf8mb4_bin DEFAULT '',
  `api_name` varchar(255) COLLATE utf8mb4_bin DEFAULT '' ,
  `api_type` int(4) NOT NULL DEFAULT 0 ,
  `check_amount` decimal(16,2) NOT NULL DEFAULT 0.00 ,
  `net_amount` decimal(16,2) NOT NULL DEFAULT 0.00 ,
  `valid_check_amount` decimal(16,2) NOT NULL DEFAULT 0.00,
  `bill_no` varchar(255) COLLATE utf8mb4_bin DEFAULT '',
  `copy_flag` int(4) NOT NULL DEFAULT 0 ,
  `flag` int(4) NOT NULL DEFAULT 0,
  `flow_quota` int(4) NOT NULL DEFAULT 0 ,
  `order_type` int(4) NOT NULL DEFAULT 0 ,
  `order_name` varchar(255) COLLATE utf8mb4_bin DEFAULT '' ,
  `is_use` int(4) NOT NULL DEFAULT 0   'is_use',
  `main_bill_no` varchar(255) COLLATE utf8mb4_bin DEFAULT '' ,
  `member_id` bigint(20) DEFAULT 0 ,
  `name` varchar(255) COLLATE utf8mb4_bin DEFAULT '' ,
  `odds` decimal(16,2) NOT NULL DEFAULT 0.00 ,
  `prefix` varchar(255) COLLATE utf8mb4_bin DEFAULT '',
  `re_amount` decimal(16,2) NOT NULL DEFAULT 0.00,
  `check_time` datetime DEFAULT NULL   ,
  `order_time` datetime DEFAULT NULL   ,
  `source_url` varchar(255) COLLATE utf8mb4_bin DEFAULT '',
  `top_id` bigint(20) DEFAULT 0 ,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP ,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_time` (`check_time`),
  KEY `idx_member_id` (`member_id`),
  KEY `idx_member_id_check_time` (`member_id`,`check_time`),
  KEY `idx_top_id` (`top_id`),
  KEY `idx_order_time_name` (`order_time`,`name`),
  KEY `CIDX_order_api_net_valid` (`order_time`,`api_name`,`net_amount`,`valid_amount`),
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci/*!90000 SHARD_ROW_ID_BITS=4 PRE_SPLIT_REGIONS=2 */ COMMENT='订单表'
1 row in set (0.00 sec)

**Comment by Ryan-Git** [comment]
增量同步？
照理没有唯一索引，4.0 默认悲观锁这个表结构不应该冲突了。咨询下 tidb 的同学吧

**Comment by Ryan-Git** [comment]
有啥进展么 @tiger-k8s

**Comment by tiger-k8s** [comment]
你好，
问题解决了，因为tikv的ssd磁盘质量差，iops 1万，导致写入慢。后来调整了ssd的配置，现在写入都正常了。


谢谢















在 2020-12-08 19:28:42，"Ryan-Git" <notifications@github.com> 写道：

有啥进展么 @tiger-k8s

**Comment by Ryan-Git** [comment]
ok
