### ISSUE TITLE
启动时候 报错"Error 1064: You have an error in your SQL syntax

### ISSUE THREAD

**Issue by shawnloong** [moiot/gravity#297]
{"level":"fatal","msg":"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*/CREATE DATABASE IF NOT EXISTS _gravity' at line 1\n/application/app/gravity/pkg/position_repos/mysql_repo.go:102: \n/application/app/gravity/pkg/inputs/mysqlstream/input.go:135: \n/application/app/gravity/pkg/app/server.go:122: ","time":"2020-11-13T15:31:33+08:00"}
[root@temp20200912-xjyc-0003 bin]#

**Comment by Ryan-Git** [comment]
mysql 版本？为啥这也报错。

**Comment by shawnloong** [comment]
> mysql 版本？为啥这也报错。
mysql 5.7.25

**Comment by Ryan-Git** [comment]
直接执行可以吗？
5.7 应该没问题的，我们自己有很多 5.7

**Comment by Ryan-Git** [comment]
没问题关了哈，看其他 issue 已经用起来了。
有问题再开。
