### ISSUE TITLE
gravity 监控对granfa版本有要求吗？

### ISSUE THREAD

**Issue by shawnloong** [moiot/gravity#299]
xxxxx:8080/metrics/api/v1/query?query=1%2B1&time=1607342761.96:1 Failed to load resource: the server responded with a status of 404 (Not Found)

5.0出现这个错误

**Comment by Ryan-Git** [comment]
我们用过 6 和 7，现在是 7。
这个报错看起来要么是请求的路径不对，要么是 Prometheus server 的问题。

**Comment by shawnloong** [comment]
是配置问题，已解决

**Comment by shawnloong** [comment]
延迟指标是关注latency这个指标吗？

**Comment by Ryan-Git** [comment]
端到端延迟是看 watermark。
定义一行完成的时刻是该行及其所有前序（binlog 确定的顺序）行都完成的时刻。
process watermark 是从进程收到 binlog 到“完成”的延迟。
event watermark 是从 binlog 时间戳到“完成”的延迟。
