### ISSUE TITLE
源库使用gh-ost是否要关闭DDL同步

### ISSUE THREAD

**Issue by shawnloong** [moiot/gravity#300]
源库使用gh-ost是否要关闭DDL同步

**Comment by Ryan-Git** [comment]
不用，会在目标侧同样生效。
如果不想同步到目标侧，那可以关掉 ddl。

现在的一个已知问题是临时表会残留，可以通过多配相应的路由解决。
https://github.com/moiot/gravity/issues/236

**Comment by shawnloong** [comment]
比如同步历史库这种场景 gh-ost最后是rename表，所以貌似只能禁用DDL同步，否则会导致历史库数据丢失，因为同步中过滤了delete操作

**Comment by Ryan-Git** [comment]
哦。。那是业务场景问题

**Comment by shawnloong** [comment]
目前 功能 没有包含数据校验功能 吧？

**Comment by Ryan-Git** [comment]
过滤 delete 咋校验。。
数据完全一致的话可以用 mysql 常用的工具校验，比如 pt-table-checksum, pingcap 的 [sync-diff-inspector](https://docs.pingcap.com/zh/tidb/stable/sync-diff-inspector-overview)
