### ISSUE TITLE
可能支持where条件过滤？

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#306]
您好，请问下，目前有个业务场景，需要根据数据的内容进行同步过滤，类似于加一个条件  where xx=‘xx’ 这类的，我看目前的文档没有这个方面的设置，这个是否考虑支持？

**Comment by Ryan-Git** [comment]
全量是支持的，增量的话目前只能用 filter

**Comment by zhanjianS** [comment]
全量和增量这个配置应该怎么写?我没有看到找到可以根据内容过滤的filter的配置

**Comment by Ryan-Git** [comment]
全量可以这样配
```yaml
[[input.config.table-configs]]
schema = "test_1"
table = "test_source_*"
condition = "v = 1"
```

增量`filter`可以用 [grpc-sidecar](https://github.com/moiot/gravity/blob/master/docs/2.0/05-filters.md#grpc-sidecar) 自己定义，也可以讨论下需求，增加新的`filter`。

**Comment by zhanjianS** [comment]
增量的需求是希望通过进行某个字段的值进行过滤的
例如：

> CREATE TABLE `testa` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_no` varchar(32）DEFAULT '' COMMENT '订单号',
  `source` int(11) DEFAULT '0' COMMENT '来源',
 `type`  int(11) DEFAULT '0' COMMENT '类型'
  PRIMARY KEY (`id`),
)

比如从表testa中同步到另一个数据源同样结构的表b中，但是我只希望同步其中某一个来源或者某一个类型的数据到testb中的数据，简单用sql话的表示就是 where souce = 1 ;   或者有多个条件 where souce = 1  and  type =1 

另外就是 同一个通道有可能有不同库不同表的不同的条件。

**Comment by Ryan-Git** [comment]
增量走的 binlog 不是扫表，配置 sql 还要解析，会很麻烦。

现有能用的就是 grpc-sidecar 了，新加的话可以内嵌个脚本，考虑 go template。

> 同一个通道有可能有不同库不同表的不同的条件

这个 filter 本来就支持的，用 matcher 匹配一下就行。

**Comment by zhanjianS** [comment]
> 
> 
> 增量走的 binlog 不是扫表，配置 sql 还要解析，会很麻烦。
> 
> 现有能用的就是 grpc-sidecar 了，新加的话可以内嵌个脚本，考虑 go template。
> 
> > 同一个通道有可能有不同库不同表的不同的条件
> 
> 这个 filter 本来就支持的，用 matcher 匹配一下就行。

condition = "v = 1"  不按照配置sql  增量的话 按照全量这种的话 配置 实现麻烦嘛

> 现有能用的就是 grpc-sidecar 了，新加的话可以内嵌个脚本，考虑 go template。

不懂go，您的意思是 我可以采用 go template。 来实现grpc-sidecar嘛

**Comment by Ryan-Git** [comment]
> condition = "v = 1" 不按照配置sql 增量的话 按照全量这种的话 配置 实现麻烦嘛

什么意思，想增量也这样配？那比较麻烦，要做表达式解析，语义也很难跟sql一样。不如用脚本。


> 不懂go，您的意思是 我可以采用 go template。 来实现grpc-sidecar嘛

不是，是新加一个`Filter`
