### ISSUE TITLE
k8s集群gravity 报错疑惑

### ISSUE THREAD

**Issue by zsp108** [moiot/gravity#307]
\# name 必填
name = "mysql2mysqlDemo"

\# 内部用于保存位点、心跳等事项的库名，默认为 _gravity
internal-db-name = "_gravity"

\#
\# Input 插件的定义，此处定义使用 mysql
\#
[input]
type = "mysql"
mode = "replication"
[input.config.source]
host = "xxxxxxxx"
username = "xxxx"
password = "xxxxx"
port = 2108

[[input.config.table-configs]]
schema = "test"
table = "*"

\#
\# Output 插件的定义，此处使用 mysql
\#
[output]
type = "mysql"
[output.config.target]
host = "xxxx"
username = "xxx"
password = "xxxx"
port = 2109

[output.config]
enable-ddl = true

\# 路由规则的定义
\#[[output.config.routes]]
\#match-schema = "test"
\#match-table = "test_source_table"
\#target-schema = "test"
\#target-table = "test_target_table"

上面是我使用源码跑的toml配置，是可以跑的，然后我用k8s配置json配置，一直创建任务提示
create pipeline failed.. err: {"error":"error Validate task spec: name must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name', or '123-abc')"}
![image](https://user-images.githubusercontent.com/31213457/105827694-44c41d80-5ffd-11eb-81d5-fb419db03587.png)

k8s配置如下：

{
  "name": "mysql2mysql",
  "internal-db-name": "_gravity",
  "input": {
    "type": "mysql",
    "mode": "replication",
    "config": {
      "source": {
        "host": "xxxxxx",
        "username": "xxxx",
        "passwprd": "xxxx",
        "port": 2108
      },
      "table-configs": {
        "schema": "test",
        "table": "*"
      }
    }
  },
  "output": {
    "type": "mysql",
    "config": {
      "source": {
        "host": "xxxx",
        "username": "xxxx",
        "passwprd": "xxxx",
        "port": 2109
      },
      "enable-ddl": "true"
    }
  }
}

想请教下这个报错具体是我哪个配置项漏了还是配置方法不对？谢谢

**Comment by Ryan-Git** [comment]
配置内容不对。

k8s 的 crd 是[这样的](https://github.com/moiot/gravity-operator/blob/master/pkg/apis/pipeline/v1alpha1/types.go)，大概就是
```json
{
"name": "xxx",
"spec":{
  "config": "这里是原来的配置"
}
}
```
编辑器里也有预置的模板可以用，点那个小箭头

**Comment by zsp108** [comment]
> 配置内容不对。
> 
> k8s的crd是[这样的](https://github.com/moiot/gravity-operator/blob/master/pkg/apis/pipeline/v1alpha1/types.go)，大概就是
> 
> ```json
> {
>  “ name ”：“ xxx ”，
>  “ spec ”：{
>    “ config ”：“这里是原来的配置”
> }
> }
> ```
> 
> 编辑器里也有预先的模板可以用，点那个小箭头

可以创建了，非常感谢解答

**Comment by zsp108** [comment]
> 配置内容不对。
> 
> k8s的crd是[这样的](https://github.com/moiot/gravity-operator/blob/master/pkg/apis/pipeline/v1alpha1/types.go)，大概就是
> 
> ```json
> {
>  “ name ”：“ xxx ”，
>  “ spec ”：{
>    “ config ”：“这里是原来的配置”
> }
> }
> ```
> 
> 编辑器里也有预先的模板可以用，点那个小箭头

可以创建了，非常感谢解答
