### ISSUE TITLE
增量出现死锁

### ISSUE THREAD

**Issue by shawnloong** [moiot/gravity#308]
Error 1213: Deadlock found when trying to get lock; try restarting transaction","time":"2021-01-26T20:35:57+08:00"}
{"level":"fatal","msg":"[batchScheduler] output exec error: Error 1213: Deadlock found when trying to get lock; try restarting transaction\n/application/app/gravity/pkg/sql_execution_engine/internal_txn_tagger.go:70: query: REPLACE INTO `pay_xxx`.`xx_order` (`id`,`......)

**Comment by Ryan-Git** [comment]
replace 在有唯一索引的情况下是有可能有死锁的，尤其是 rr 级别，建议用 rc。
