### ISSUE TITLE
Mysql 同步到Kafka，出现item not ack

### ISSUE THREAD

**Issue by zhanglei** [moiot/gravity#309]
数据一直卡在这里，使用场景全量从mysql读数据写入kafka中，读600多万数据时就会出现这个（item not ack after ）
[sliding_window] item not ack after 63.422989 seconds

重启后恢复正常，但继续跑数据时还会出现
有开启日志定位，在这段代码中出现拿到6703850这个消息时未执行pop
<img width="882" alt="image" src="https://user-images.githubusercontent.com/241508/108597621-ee13ee80-73c4-11eb-9ecc-e64ff12f93c4.png">
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/241508/108597624-f10edf00-73c4-11eb-9e3f-ff378f594195.png">

BeforeWindowMoveForward方法的代码看了下，应该没什么大问题

**Comment by zhanglei** [comment]
出现这个时，整个进程 hang 死状态
试过output stdout场景时也会出现这个问题

**Comment by Ryan-Git** [comment]
卡死的时候看下栈
http://localhost:8080/debug/pprof/goroutine

**Comment by zhanglei** [comment]
![image](https://user-images.githubusercontent.com/241508/108621974-f32e7780-7470-11eb-91b9-bcf92b9a88b0.png)

**Comment by zhanglei** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/241508/108622079-74860a00-7471-11eb-886a-bcdf03f03f68.png">

**Comment by zhanglei** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/241508/108622096-849de980-7471-11eb-8b74-6f018e99f856.png">

**Comment by zhanglei** [comment]
从代码上分析应该是出现死锁了
PutCurrentPos与EncodeBatchPositionValue

**Comment by zhanglei** [comment]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/241508/108649863-261c4e00-74f9-11eb-9fed-823e1b229e6f.png">
与https://github.com/moiot/gravity/pull/296 的代码修改关系比较大，去掉这里锁就正常

**Comment by Ryan-Git** [comment]
我想想怎么改，去掉也有问题。

**Comment by Ryan-Git** [comment]
他俩只是都在等锁，持有锁的是哪个栈？

**Comment by hoslo** [comment]
> 我想怎么改，删除也有问题。

请问有解决方法了吗，我也遇到了这个问题

**Comment by Ryan-Git** [comment]
> > 我想怎么改，删除也有问题。
> 
> 请问有解决方法了吗，我也遇到了这个问题

临时可以先回撤这个改动 https://github.com/moiot/gravity/pull/296/files

**Comment by hoslo** [comment]
> > > 我想怎么改，删除也有问题。
> > 
> > 
> > 请问有解决方法了吗，我也遇到了这个问题
> 
> 临时可以先回撤这个改动 https://github.com/moiot/gravity/pull/296/files

我试过，去掉这个好像会导致数据重复的问题，还是我其他地方设置不对

**Comment by Ryan-Git** [comment]
重复是什么意思？

**Comment by hoslo** [comment]
> 重复是什么意思？

多个表合并到一个表中，出现了重复的数据，数据量比原表几个加起来还多

**Comment by Ryan-Git** [comment]
看下表结构吧，这种可能是主键/唯一键设得有问题
