### ISSUE TITLE
mongodb同步到tidb 

### ISSUE THREAD

**Issue by BruceChinese** [moiot/gravity#311]
![image](https://user-images.githubusercontent.com/12492229/111114229-e8fa2780-859d-11eb-84df-47eb83ddb382.png)

在tidb里没有数据 一直是这种状态 

name = "mongo2tidb"

[input]
type = "mongo"
mode = "stream"
[input.config.source]
host  = "1xxx"
username = "xxx"
password = "xxx"
port = xxxx

[output]
type = "mysql"
[output.config.target]
host = "xxxx"
username = "xxx"
password = "xxxx"
port =xxxx

[[output.config.routes]]
match-schema = "post"
match-table = "*"
target-schema = "post"
#target-table = "post"

**Comment by Ryan-Git** [comment]
这是增量，启动之后 mongo 有更新吗？

**Comment by BruceChinese** [comment]
有  业务库 更新很快  tidb需要手动建库建表吗

**Comment by BruceChinese** [comment]
这个支持mongodb sharding吗

**Comment by Ryan-Git** [comment]
> 有 业务库 更新很快 tidb需要手动建库建表吗

要的。


> 这个支持mongodb sharding吗

可以每个分片一个单独的进程。只连 mongos 的话不行。
