### ISSUE TITLE
分库分表合并到单库单表数据被覆盖

### ISSUE THREAD

**Issue by zsp108** [moiot/gravity#312]
使用的是k8s搭建的gravity，总共三个库，ztest.mage,zz.mage 是测试的源端分片库表，gtest.mage是目标端的合并库表，
对这两个分片新建两条replication模式的合并任务，第一条同步任务传输数据成功后，第二条任务配置开启后把第一条任务同步的数据给覆盖了，想问下是否有分库分片合并的文档可以提供学习下？或者帮忙看下我参数内是否有配置错误的地方？非常感谢

![image](https://user-images.githubusercontent.com/31213457/114492872-088f7900-9c4c-11eb-8a5a-ff1f6c2a3bcc.png)

配置文件（两个配置任务除了数据库名不同外，其他都一样）：
`{
	"metadata": {
		"name": "gtest"
	},
	"spec": {
		"config": {
			"version": "1.0",
			"input": {
				"type": "mysql",
				"mode": "replication",
				"config": {
					"batch-per-second-limit": 10,
					"nr-scanner": 10,
					"table-scan-batch": 1000,
					"source": {
						"host": "192.168.xx.xxx",
						"port": 3008,
						"username": "xxx",
						"password": "xxx"
					}
				}
			},
			"output": {
				"type": "mysql",
				"config": {
					"enable-ddl": false,
					"routes": [
						{
							"match-schema": "ztest",
							"match-table": "mage",
							"target-schema": "gtest",
							"target-table": "mage"
						}
					],
					"target": {
						"host": "192.168.xx.xxx",
						"port": 3008,
						"username": "xxx",
						"password": "xxx"
					}
				}
			},
			"scheduler": {
				"type": "batch-table-scheduler",
				"config": {
					"batch-size": 1,
					"nr-worker": 10,
					"queue-size": 1024,
					"sliding-window-size": 10240
				}
			}
		}
	}
}`

**Comment by zsp108** [comment]
上面的配置信息乱了，重新提交下配置
{
	"metadata": {
		"name": "gtest"
	},
	"spec": {
		"config": {
			"version": "1.0",
			"input": {
				"type": "mysql",
				"mode": "replication",
				"config": {
					"batch-per-second-limit": 10,
					"nr-scanner": 10,
					"table-scan-batch": 1000,
					"source": {
						"host": "192.168.xx.xxx",
						"port": 3008,
						"username": "xxx",
						"password": "xxx"
					}
				}
			},
			"output": {
				"type": "mysql",
				"config": {
					"enable-ddl": false,
					"routes": [
						{
							"match-schema": "ztest",
							"match-table": "mage",
							"target-schema": "gtest",
							"target-table": "mage"
						}
					],
					"target": {
						"host": "192.168.xx.xxx",
						"port": 3008,
						"username": "xxx",
						"password": "xxx"
					}
				}
			},
			"scheduler": {
				"type": "batch-table-scheduler",
				"config": {
					"batch-size": 1,
					"nr-worker": 10,
					"queue-size": 1024,
					"sliding-window-size": 10240
				}
			}
		}
	}
}

**Comment by zsp108** [comment]
``{
	"metadata": {
		"name": "gtest"
	},
	"spec": {
		"config": {
			"version": "1.0",
			"input": {
				"type": "mysql",
				"mode": "replication",
				"config": {
					"batch-per-second-limit": 10,
					"nr-scanner": 10,
					"table-scan-batch": 1000,
					"source": {
						"host": "192.168.xx.xxx",
						"port": 3008,
						"username": "xxx",
						"password": "xxx"
					}
				}
			},
			"output": {
				"type": "mysql",
				"config": {
					"enable-ddl": false,
					"routes": [
						{
							"match-schema": "ztest",
							"match-table": "mage",
							"target-schema": "gtest",
							"target-table": "mage"
						}
					],
					"target": {
						"host": "192.168.xx.xxx",
						"port": 3008,
						"username": "xxx",
						"password": "xxx"
					}
				}
			},
			"scheduler": {
				"type": "batch-table-scheduler",
				"config": {
					"batch-size": 1,
					"nr-worker": 10,
					"queue-size": 1024,
					"sliding-window-size": 10240
				}
			}
		}
	}
}

**Comment by zsp108** [comment]
```json
{
    "metadata": {
		"name": "gtest"
	},
	"spec": {
		"config": {
			"version": "1.0",
			"input": {
				"type": "mysql",
				"mode": "replication",
				"config": {
					"batch-per-second-limit": 10,
					"nr-scanner": 10,
					"table-scan-batch": 1000,
					"source": {
						"host": "192.168.xx.xxx",
						"port": 3008,
						"username": "xxx",
						"password": "xxx"
					}
				}
			},
			"output": {
				"type": "mysql",
				"config": {
					"enable-ddl": false,
					"routes": [
						{
							"match-schema": "ztest",
							"match-table": "mage",
							"target-schema": "gtest",
							"target-table": "mage"
						}
					],
					"target": {
						"host": "192.168.xx.xxx",
						"port": 3008,
						"username": "xxx",
						"password": "xxx"
					}
				}
			},
			"scheduler": {
				"type": "batch-table-scheduler",
				"config": {
					"batch-size": 1,
					"nr-worker": 10,
					"queue-size": 1024,
					"sliding-window-size": 10240
				}
			}
		}
	}
}

```

**Comment by Ryan-Git** [comment]
这跟同步没啥关系，主键一样了。
要么合库不用原来的主键，要么分库主键不要重复。不重复可以让 auto increment 步长不一样，或者用发号器。

**Comment by zsp108** [comment]
试了下新增一个字段做主键确实可以了，多谢回复，另外想问下gravity是否支持列映射操作？如果存在唯一键冲突的话也会出现一样的情况吧？
还有我看到Filter应该是针对增量数据的吧？
https://github.com/moiot/gravity/blob/master/docs/2.0/05-filters.md

**Comment by Ryan-Git** [comment]
合表新增主键的话原分表必须有唯一键，而且唯一键必须在所有分库唯一，不然同步会有一样的问题。

filter 不区分全量增量，一样的。

**Comment by zsp108** [comment]
好的，多谢
