### ISSUE TITLE
mysql源端使用replace into语句时，mysql->kafka 有时会获取不到变更日志，mysql->mysql也会偶尔出现数据丢失的情况

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#315]
遇到一个场景，mysql源端使用replace into语句时，mysql->kafka 有时会获取不到变更日志，mysql->mysql也会偶尔出现数据丢失的情况，mysql端使用insert into时候就正常

**Comment by Ryan-Git** [comment]
怎么复现？

**Comment by zhanjianS** [comment]
昨晚试了下  没能复现。我先关了吧  等发现了在说
