### ISSUE TITLE
mysql同步到tidb 延迟大的问题

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#316]
当 mysql端有大批量的数据导入， 同步有很大的延迟
日志一直是如下：

![图片](https://user-images.githubusercontent.com/31116868/123089785-fc007b80-d459-11eb-8067-fbbaeca0d57e.png)

监控截图:

![图片](https://user-images.githubusercontent.com/31116868/123089559-ad52e180-d459-11eb-97f2-abe5e1af1f18.png)
![图片](https://user-images.githubusercontent.com/31116868/123089608-be9bee00-d459-11eb-9a84-4630a2d1aabf.png)

**Comment by Ryan-Git** [comment]
tidb 那里是不是有很多 resolve lock。监控看是有些行特别慢阻塞了整个流水线。

输出端并发是多少？配置贴一下。写 tidb 和写 mysql 不太一样，并发要开高一点才行。

**Comment by zhanjianS** [comment]
这个是tidb的监控 不知道是不是您所说的resolve lock
![图片](https://user-images.githubusercontent.com/31116868/123101397-99fa4300-d466-11eb-9221-fe33329e6616.png)

输出配置如下：
    "scheduler": {
      "type": "batch-table-scheduler",
      "config": {
        "batch-size": 90,
        "healthy-threshold": 3600,
        "nr-worker": 100,
        "queue-size": 10240,
        "sliding-window-size": 10240
      }
    }

nr-worker 尝试调到200过  没起作用

**Comment by Ryan-Git** [comment]
把`output.config.target.max-open`, `output.config.target.max-idle`, `scheduler.nr-worker` 都改成 200 试试。

output 默认的 mysql 配置只开 20 连接，不太适合 tidb。

**Comment by zhanjianS** [comment]
配置了这个参数 重启任务半个小时后  任务的处理数据量开始上来了

**Comment by Ryan-Git** [comment]
要过半小时有点奇怪，真是并发不够的话应该立即生效的。再观察下。
