### ISSUE TITLE
请问一下，双向同步防止循环原理是什么呢？

### ISSUE THREAD

**Issue by decadestory** [moiot/gravity#333]
请问一下，双向同步防止循环原理是什么呢？

**Comment by Ryan-Git** [comment]
一般有两种做法。
一是同步时候开事务，先往系统内部预定义的表更新一行，这样在 binlog 里可以识别出是同步流量，不再往回同步。
二是 binlog 记录原 sql 语句，同步的语句加个注释，这样就也可以识别出。

由于同步语句较长，综合考虑事务开销和 binlog 开销我们采用的方案一。实际性能差距不是很大。

**Comment by decadestory** [comment]
谢谢及时回复，我准备尝试一下方案二，希望你们继续加油，争取支持更多的输出端

**Comment by Ryan-Git** [comment]
感谢
