### ISSUE TITLE
CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 问题

### ISSUE THREAD

**Issue by zeusYi** [moiot/gravity#335]
表结构
```sql
CREATE TABLE `t1` (
  `id` bigint NOT NULL COMMENT '主键',
  `vch_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `vch_no` (`vch_no`) USING BTREE,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC 
```

源端数据
mysql> SELECT id,create_time,update_time from `t1` where id=541361509175918640\G;
*************************** 1. row ***************************
         id: 541361509175918640
create_time: 2022-08-15 01:37:27
update_time: 2022-08-15 01:37:27
1 row in set (0.00 sec)

ERROR: 
No query specified

作业配置

{"name": "dts.pHtRQf72xEJx", "input": {"mode": "replication", "type": "mysql", "config": {"source": {"host": "10.50.101.130", "port": 26223, "timeout": "300s", "password": "root123", "username": "root", "read-timeout": "300s", "write-timeout": "300s"}, "nr-scanner": 4, "ignore-tables": null, "table-configs": [{"table": ["*"], "schema": "dtstest", "condition": ""}], "table-scan-batch": 10000, "max-full-dump-count": 1000000, "is-enable-batch-scan": true, "batch-per-second-limit": 2}}, "output": {"type": "mysql", "config": {"routes": [{"dml-topic": "", "match-table": "*", "match-schema": "dtstest", "target-table": "", "target-schema": "dtstest"}], "target": {"host": "10.50.101.130", "port": 26224, "timeout": "300s", "password": "root123", "username": "root", "read-timeout": "300s", "write-timeout": "300s"}, "enable-ddl": true, "execution-engine": {"use-bidirection": false, "use-shading-proxy": false}, "kafka-global-config": null}}, "scheduler": {"type": "batch-table-scheduler", "config": {"nr-worker": 100, "batch-size": 1000, "queue-size": 4096, "sliding-window-size": 10240}}, "internal-db-name": "_dts"}

目标端回放的时候抓取的general log 日志
REPLACE INTO `dtstest`.`t1` (`id`,`vch_no`,`create_time`,`update_time`,`del_flag`) VALUES (540358079040979086,'600020534222',DEFAULT,DEFAULT,0)

目标库数据：
mysql> SELECT * FROM `dtstest`.`t1` WHERE id >= 541361509175918640 AND id <= 552905533338681356 LIMIT 1\G;
*************************** 1. row ***************************
          id: 541361509175918640
      vch_no: 000168088943
      vch_id: 1
 create_time: 2022-08-16 09:49:36
 update_time: 2022-08-16 09:49:36
    del_flag: 0
1 row in set (0.00 sec)

**Comment by Ryan-Git** [comment]
我试了下没有复现，无论增量还是全量都能正常同步的
目标表结构再贴一下？

**Comment by Ryan-Git** [comment]
讨论了下，是老版本的一个问题，主干已经修复。

问题是 MySQL 8.0 版本 DEFAULT CURRENT_TIMESTAMP 会在 information schema 的 extra 里标记 default generated，之前的版本不会。用户使用的 gravity 版本是用 contains generated 来判断是否是生成列的，造成了误判。主干上是用 stored generated 判断的，所以没有这个问题。
