### ISSUE TITLE
Unknown character set

### ISSUE THREAD

**Issue by huyongywl** [moiot/gravity#343]
你好，这个错是不支持这个字符集的意思吗？
{"level":"info","msg":"[Server] started","time":"2023-05-10T15:34:10+08:00"}
{"level":"fatal","msg":"[parser:1115]Unknown character set: 'utf8mb3'","time":"2023-05-10T15:34:10+08:00"}

**Comment by Ryan-Git** [comment]
用 utf8 或者 utf8mb4

**Comment by huyongywl** [comment]
> 用 utf8 或者 utf8mb4

这个是要改input库表的字符集吗？还是说gravity支持设置字符集

**Comment by Ryan-Git** [comment]
上游是 MySQL 8.0？改成 utf8mb4, mb3 本来也废弃了。

> You should also be aware that the utf8mb3 character set is deprecated and you should expect it to be removed in a future MySQL release. Please use utf8mb4 instead.

https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html

报错原因是 parser 用的 tidb 的，tidb 还不支持 mb3。具体哪个地方调的日志里没看出来，可以打下栈。

**Comment by huyongywl** [comment]
好的，我改下编码吧，谢谢了

**Comment by Ryan-Git** [comment]
好，那先关了
