### ISSUE TITLE
采集带有unikey的到kafka处理时间还是长（最新代码）

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#345]
采集带有unikey的到kafka处理时间还是长（最新代码）

日志一直是这个
![图片](https://github.com/moiot/gravity/assets/31116868/fe02839e-6441-49c7-b341-d2148d11a3a7)

监控页面
![图片](https://github.com/moiot/gravity/assets/31116868/c4d4b682-1f3a-40d6-8d26-8532f9e98e8e)
![图片](https://github.com/moiot/gravity/assets/31116868/71963b17-ec9d-447d-9daa-f04ef6bd2874)

代码已经最近版本  https://github.com/moiot/gravity/issues/334 这个里面修复的最新版本了

过滤掉删除操作后。就会很快，

![图片](https://github.com/moiot/gravity/assets/31116868/bbeb33b0-8fc2-446a-8403-8feb4a983c6e)

源端是通过repalce into 插入的数据。我看底层会生成delete及insert 两条日志
  看数据也是输出段是 输入的一半。
是删除操作会阻塞吗？

**Comment by Ryan-Git** [comment]
replace 产生的 delete 肯定会阻塞 insert

**Comment by zhanjianS** [comment]
> replace 产生的 delete 肯定会阻塞 insert

大佬 我之前过滤掉delete 操作数据恢复正常了， 但是今天突发这种更新很慢的问题 是为啥，还是类似同样的日志，数据是同步给kafka的
![图片](https://github.com/moiot/gravity/assets/31116868/29b649ca-6ba4-40ee-9329-bc1cd527ad51)

**Comment by Ryan-Git** [comment]
updatePrimaryKey 是有主键更新，会拆成先 delete 再 update
为什么慢要贴监控

**Comment by zhanjianS** [comment]
> updatePrimaryKey 是有主键更新，会拆成先 delete 再 update 为什么慢要贴监控

![图片](https://github.com/moiot/gravity/assets/31116868/620dab22-539d-4549-946d-aceb4add21b6)
![图片](https://github.com/moiot/gravity/assets/31116868/5fd9764f-446e-446f-a622-6a16801a9a45)

![Uploading 图片.png…]()

**Comment by Ryan-Git** [comment]
冲突队列很长。
给个最小复现的例子吧。表结构，执行什么样的 sql。

**Comment by zhanjianS** [comment]
> 冲突队列很长。 给个最小复现的例子吧。表结构，执行什么样的 sql。

CREATE TABLE `bigdatamk_api_label_user_detail_duplicate_4` (
	`id` BIGINT ( 20 ) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
	`label_id` VARCHAR ( 32 ) COLLATE utf8mb4_bin NOT NULL COMMENT '标签ID',
	`customer_id` VARCHAR ( 64 ) COLLATE utf8mb4_bin NOT NULL COMMENT '会员ID',
	`statistics_date` date NOT NULL COMMENT '',
	`label_status` INT ( 11 ) NOT NULL COMMENT '',
	`group_id` BIGINT ( 20 ) NOT NULL COMMENT '',
	`seller_id` BIGINT ( 20 ) DEFAULT NULL COMMENT '',
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY ( `id` ),
UNIQUE KEY `uniq_user_label` ( `customer_id`, `label_id` ),
KEY `idx_label_id` ( `label_id` )) ENGINE = INNODB AUTO_INCREMENT = 917784618319240790 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin COMMENT = '标签用户明细数据'


数据是执行replace into 操作
