### ISSUE TITLE
采用K8s部署，突然不可以新增任务了

### ISSUE THREAD

**Issue by zhanjianS** [moiot/gravity#350]
请教下 新增任务一直卡在如图这个，没有相关的错误日志，对应pod 没拉起来，
![图片](https://github.com/moiot/gravity/assets/31116868/a729c59c-3056-46d3-ad28-e1c20d682f6c)

gravity-operator的相关日志

![图片](https://github.com/moiot/gravity/assets/31116868/22295808-9bef-4732-9235-52e53f3fccef)

另外之前新增的任务还是可以运行 
这个怎么排查

**Comment by Ryan-Git** [comment]
看下 operator 的栈，看下 crd 建了没

**Comment by zhanjianS** [comment]
crd是指什么， 上面的截图就是operator的日志，目前只看到这种日志，在重复打， 

![图片](https://github.com/moiot/gravity/assets/31116868/1135772a-b03d-4280-aaa7-cc1c19685d13)


当时看 k8s后台的pod没有拉起来，今天看pod是有了，看pod的启动时间 比我从页面创建要晚好几个小时
![图片](https://github.com/moiot/gravity/assets/31116868/13df283b-3bce-4079-82dc-d7ad3cf96e81)

但是页面上
还是这样，没有显示运行正常，时间过了很长时间，之前是有分钟级别的延迟
![图片](https://github.com/moiot/gravity/assets/31116868/d18191e6-5d96-48c3-b012-ec79b9c18328)

**Comment by Ryan-Git** [comment]
crd 是`CustomResourceDefinition`，每个任务对应一个`Pipeline` `CRD` 的实例。要运维的话还是得了解一下 k8s。
grep 一下任务名（t5-assistant01-tidb-1）所有的日志看看。
光这样看不出啥，重启 operator，删了重建都试试。。。
