### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by xc1989xc** [moiot/gravity#352]
依赖包下载不下来，已经用了goproxy
例如
github.com/juju/errors
github.com/pingcap/errors
sourcegraph.com/sourcegraph/appdash

**Comment by Ryan-Git** [comment]
我找了个 go 也没有的新环境试了下是可以的，请检查您的配置
GOPROXY='https://goproxy.cn,direct'
...
go: downloading github.com/juju/errors v0.0.0-20170703010042-c7d06af17c68
...
go: downloading github.com/pingcap/errors v0.11.5-0.20190809092503-95897b64e011
...

**Comment by xc1989xc** [comment]
我试试 谢谢
