### ISSUE TITLE
双数据中心只同步DDL的需求

### ISSUE THREAD

**Issue by zeusYi** [moiot/gravity#38]
1. Match specific DDL statement

2. Use hint in SQL to tag the internal DDL, so that we can synchronize DDL bidirectional.

-----------------------------
需求1：两个数据源A，B，需要在A库的DDL同步到B库，B库的DDL同步到A库，目前该需求可以通过filter
[[filters]]
type = "reject"
match-dml-op = ["insert", "update", "delete"]
临时解决，
但是仍存在写循环的问题，即A生成的DDL通过binlog同步到B库，但是B库自己写入的binlog，会反向同步到A库，此时B->A的复制链路就会因为冲突而出错。

郁白给出的建议是通过gravity执行的SQL通过加hint的方式标记，B->A链路在处理B库产生的binlog的时候通过hint过滤，不再处理通过gravity执行的SQL，来解决写循环的问题。

需求2：细粒度区分DDL类型，create-table、alter table add 、 alter table drop ，alter table modify ....。 提供matcher 进行过滤同步指定哪一类的DDL type。

**Comment by ming535** [comment]
seems straight forward to support this, need some time to add a new matcher, and test the DDL tag with hint.

- [ ] New Matcher to match DDL operation

- [x] Ignore DDL if it has some specific hint

**Comment by Ryan-Git** [comment]
I've tested hint in ddl. It's ok.

About matcher, shall we use regex or type code? for now, the parser hasn't fully support all types.

**Comment by ming535** [comment]
> I've tested hint in ddl. It's ok.
> 
> About matcher, shall we use regex or type code? for now, the parser hasn't fully support all types.

Is there any open source example exists?

**Comment by Ryan-Git** [comment]
I'm not sure. Vitess might have stronger parser.

**Comment by Ryan-Git** [comment]
@yiwenshuo 
双向DDL已经合到master了。
关于匹配DDL，用正则你觉得咋样？类型实在有点多。 @ming-relax 觉得呢

**Comment by ming535** [comment]
> @yiwenshuo
> 双向DDL已经合到master了。
> 关于匹配DDL，用正则你觉得咋样？类型实在有点多。 @ming-relax 觉得呢

行啊，先用正则搞起吧

**Comment by zeusYi** [comment]
@Ryan-Git @ming-relax  两位好，我拉取了最新的master 分支，分支版本：
Release Version (gravity): 0.0.1+git.39709a1
Git Commit Hash: 39709a17fa5a1cf294128e2f4a28fb33d06aad55
Git Branch: master
UTC Build Time: 2019-01-18 06:09:20。

进行单向DDL测试的发现，alter table 可以同步，但是create table 无法同步，gravity 报错，建表DDL:
` CREATE TABLE t6 (
  id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  thirdparty tinyint(2) NOT NULL DEFAULT '0' COMMENT '第三方编号',
  related_id bigint(20) NOT NULL COMMENT '关联id',
  api varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '接口地址',
  request text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '请求参数',
  response text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '响应体',
  response_type tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '第三方调用的结果  0：未命中未成功  1：成功未命中  2：未成功命中  3、成功且命中',
  fee_for_call int(11) unsigned NOT NULL DEFAULT '0' COMMENT '当次调用的费用,防止保存小数真实结果需除以100',
  http_response_code int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'http 返回码',
  ctime bigint(20) NOT NULL COMMENT '记录创建时间',
  PRIMARY KEY (id),
  KEY related_id (related_id),
  KEY ctime (ctime),
  KEY thirdparty (thirdparty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方调用记录' `

报错信息：

`{"file":"binlog_tailer.go","level":"info","line":405,"msg":"QueryEvent: database: ywsdb, sql: CREATE TABLE t6 (\n  id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',\n  thirdparty tinyint(2) NOT NULL DEFAULT '0' COMMENT '第三方编号',\n  related_id bigint(20) NOT NULL COMMENT '关联id',\n  api varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '接口地址',\n  request text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '请求参数',\n  response text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '响应体',\n  response_type tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '第三方调用的结果  0：未命中未成功  1：成功未命中  2：未成功命中  3、成功且命中',\n  fee_for_call int(11) unsigned NOT NULL DEFAULT '0' COMMENT '当次调用的费用,防止保存小数真实结果需除以100',\n  http_response_code int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'http 返回码',\n  ctime bigint(20) NOT NULL COMMENT '记录创建时间',\n  PRIMARY KEY (id),\n  KEY related_id (related_id),\n  KEY ctime (ctime),\n  KEY thirdparty (thirdparty)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方调用记录'","pipeline":"dts_full_mysql","time":"2019/01/18 15:02:38.589"}
{"file":"db_position_store.go","level":"info","line":92,"msg":"[dbPositionStore.savePosition] succeed: stream, {\"current_position\":{\"binlog-name\":\"mysql-bin.000024\",\"binlog-pos\":54270112,\"binlog-gtid\":\"05470c3e-01c7-11e9-9a47-000c291405ef:1-442178\"},\"start_position\":{\"binlog-name\":\"mysql-bin.000024\",\"binlog-pos\":54240311,\"binlog-gtid\":\"05470c3e-01c7-11e9-9a47-000c291405ef:1-442145\"}}","pipeline":"dts_full_mysql","time":"2019/01/18 15:02:38.595"}
{"file":"mysql.go","level":"fatal","line":173,"msg":"[output-mysql] error exec ddl: CREATE TABLE IF NOT EXISTS `ywsdb`.`t6` (. err:Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1","pipeline":"dts_full_mysql","time":"2019/01/18 15:02:38.595"}`

**Comment by Ryan-Git** [comment]
> @Ryan-Git @ming-relax 两位好，我拉取了最新的master 分支，分支版本：
> Release Version (gravity): 0.0.1+git.39709a1
> Git Commit Hash: [39709a1](https://github.com/moiot/gravity/commit/39709a17fa5a1cf294128e2f4a28fb33d06aad55)
> Git Branch: master
> UTC Build Time: 2019-01-18 06:09:20。
> 
> 进行单向DDL测试的发现，alter table 可以同步，但是create table 无法同步，gravity 报错，建表DDL:
> `CREATE TABLE t6 ( id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id', thirdparty tinyint(2) NOT NULL DEFAULT '0' COMMENT '第三方编号', related_id bigint(20) NOT NULL COMMENT '关联id', api varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '接口地址', request text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '请求参数', response text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '响应体', response_type tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '第三方调用的结果 0：未命中未成功 1：成功未命中 2：未成功命中 3、成功且命中', fee_for_call int(11) unsigned NOT NULL DEFAULT '0' COMMENT '当次调用的费用,防止保存小数真实结果需除以100', http_response_code int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'http 返回码', ctime bigint(20) NOT NULL COMMENT '记录创建时间', PRIMARY KEY (id), KEY related_id (related_id), KEY ctime (ctime), KEY thirdparty (thirdparty) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方调用记录'`
> 
> 报错信息：
> 
> `{"file":"binlog_tailer.go","level":"info","line":405,"msg":"QueryEvent: database: ywsdb, sql: CREATE TABLE t6 (\n id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',\n thirdparty tinyint(2) NOT NULL DEFAULT '0' COMMENT '第三方编号',\n related_id bigint(20) NOT NULL COMMENT '关联id',\n api varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '接口地址',\n request text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '请求参数',\n response text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '响应体',\n response_type tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '第三方调用的结果 0：未命中未成功 1：成功未命中 2：未成功命中 3、成功且命中',\n fee_for_call int(11) unsigned NOT NULL DEFAULT '0' COMMENT '当次调用的费用,防止保存小数真实结果需除以100',\n http_response_code int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'http 返回码',\n ctime bigint(20) NOT NULL COMMENT '记录创建时间',\n PRIMARY KEY (id),\n KEY related_id (related_id),\n KEY ctime (ctime),\n KEY thirdparty (thirdparty)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方调用记录'","pipeline":"dts_full_mysql","time":"2019/01/18 15:02:38.589"} {"file":"db_position_store.go","level":"info","line":92,"msg":"[dbPositionStore.savePosition] succeed: stream, {\"current_position\":{\"binlog-name\":\"mysql-bin.000024\",\"binlog-pos\":54270112,\"binlog-gtid\":\"05470c3e-01c7-11e9-9a47-000c291405ef:1-442178\"},\"start_position\":{\"binlog-name\":\"mysql-bin.000024\",\"binlog-pos\":54240311,\"binlog-gtid\":\"05470c3e-01c7-11e9-9a47-000c291405ef:1-442145\"}}","pipeline":"dts_full_mysql","time":"2019/01/18 15:02:38.595"} {"file":"mysql.go","level":"fatal","line":173,"msg":"[output-mysql] error exec ddl: CREATE TABLE IF NOT EXISTS `ywsdb`.`t6` (. err:Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1","pipeline":"dts_full_mysql","time":"2019/01/18 15:02:38.595"}`

#55 will fix this. wait a moment.
