### ISSUE TITLE
could also provide the sample from MySQL to TiDB?

### ISSUE THREAD

**Issue by DamonYellow** [moiot/gravity#48]
As titled, thx

**Comment by DamonYellow** [comment]
as titled, thx

**Comment by Ryan-Git** [comment]
@DamonYellow 
Now it's the same as mysql2mysql, since TiDB uses mysql protocol. Only to mention that you could(and should) allow more connections to it than mysql.

**Comment by DamonYellow** [comment]
thx @Ryan-Git , is it possible to change the primary key while synchronizing?

**Comment by Ryan-Git** [comment]
> thx @Ryan-Git , is it possible to change the primary key while synchronizing?

@DamonYellow It's possible using `manual-engine` to write any sql you like, but it's a bit complicated. Why do you need to change pk?

For syncing sharding tables into combined one into TiDB,  we usually find out a new pk(often a unique key previously), ignore the original auto-increment id using `delete-dml-column` filter.

**Comment by DamonYellow** [comment]
because we have auto-increment pk in sharding tables, thx, let me check if I can find any sample.

**Comment by Ryan-Git** [comment]
@DamonYellow 
I'll close this for now. Further information available upon request.
