### ISSUE TITLE
create table DDL not support default value for datetime/timestamp with explicit fractional seconds precision

### ISSUE THREAD

**Issue by Ryan-Git** [moiot/gravity#59]
the argument for function current_timestamp() is lost after parsing. waiting for response from https://github.com/pingcap/parser/issues/186

**Comment by Ryan-Git** [comment]
now it's waiting for https://github.com/pingcap/parser/pull/214

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/parser/pull/214 is merged now, thanks for your contribution! @Ryan-Git

**Comment by Ryan-Git** [comment]
Thanks @tiancaiamao .
@ming-relax could you upgrade the parser and tidb lib along with #138 ?

**Comment by ming535** [comment]
parser's ci is broken
