### ISSUE TITLE
detect circular when using bidirection pipeline

### ISSUE THREAD

**Issue by ming535** [moiot/gravity#75]

**Comment by Ryan-Git** [comment]
I've confirmed that using annotation to detect circular is feasible.
- `binlog_rows_query_log_events` could be opened at session level.
- go-mysql has `RowsQueryEvent` that capture the logged sql.

So we can do following to detect circular:

- [ ] in mysql stream input, capture `RowsQueryEvent`, extract pipeline names in annotation, ignore the whole transaction if it's sent by self, or it's configured to ignore.
- [ ] add field to `Msg`, save the extracted pipeline names.
- [ ] set `binlog_rows_query_log_events` in mysql output upon connection.
- [ ] add annotation to the executed sql, e.g. `/*gravity:{pipelineNames}*/`. **EACH** extracted pipeline, along with the current one should be added.

We can apply similar mechanism to the current transnational way to detect circular, too. Just capture and write all pipeline names in the transaction.

Investigation is still needed to see which one has lower cost. Rows query event could be much larger than the update and table map event of `_gravity_txn_tags`(the logged sql is a full column replace while `_gravity_txn_tags` have only 4 columns), but it avoids transaction overhead.

It's quite a few work. I'm wondering whether to include it in 1.0 milestone.

**Comment by imjustfly** [comment]
@Ryan-Git 

For MariaDB, detecting circular needs `BINLOG_SEND_ANNOTATE_ROWS_EVENT `, but it's not captured by go-mysql now. I committed a PR  (https://github.com/siddontang/go-mysql/pull/371) for it.

**Comment by Ryan-Git** [comment]
@imjustfly 
thanks. we'll keep an eye on it.

**Comment by Ryan-Git** [comment]
this is done with config `fail-on-txn-tags`
