### ISSUE TITLE
Could you provide a binary package for special environment，eg Production Which not allow connect to Internet，or I Just want to download it to Use. Do you Have QQ group or wechat group to talk about Gravity？

### ISSUE THREAD

**Issue by vkingnew** [moiot/gravity#96]

**Comment by Ryan-Git** [comment]
you could build by yourself. (`make` will build for ur current arch, for cross-compile you could check `make build-linux`)

we have a wechat group.
![image](https://user-images.githubusercontent.com/5906907/53319433-74e47c80-390d-11e9-95a3-d0e90f0f5e02.png)

**Comment by vkingnew** [comment]
Thanks,I will try!

**Comment by zhangchangwei** [comment]
@vkingnew 可以分享下微信群吗
